/* ============================================================================
 * XVT -> Qt COMPATIBILITY LAYER  (flagged file: see qt_compat/README.md)
 *
 * AUTO-GENERATED by scratchpad/gen_dialog_registry.py from nodInc.h -- DO
 * NOT HAND-EDIT. Regenerate by re-running that script against nodInc.h.
 *
 * nodInc.h's constant names were themselves auto-generated by XVT-Design
 * from the (missing, see qt_compat/README.md) compiled resource file, in
 * the form <WINDOW>_<WIDGETTYPE>_<seq>, e.g. WIN_116_CHECKBOX_68 or
 * GEOLOGY_OPTIONS_WINDOW_C13. That means the exact widget TYPE of nearly
 * every control in every one of this app's ~150 dialogs is recoverable
 * from the header alone, even though exact pixel positions/sizes are not
 * (those lived only in the missing resource file). This table is that
 * recovered type information, consumed by xvt_compat.cpp to build each
 * dialog's real controls (instead of an empty placeholder window) the
 * first time the app asks for it.
 * ============================================================================
 */
#include "xvt_types.h"

struct DialogCtlEntry { int ctlId; WIN_TYPE type; const char *label; };
struct DialogEntry { long resId; const char *title; const DialogCtlEntry *ctls; int numCtls; };

static const DialogCtlEntry g_ctls_104[] = {
    { 1, WC_HSCROLL, "WIN 104 HSCROLL 5" },
    { 2, WC_HSCROLL, "WIN 104 HSCROLL 6" },
    { 3, WC_HSCROLL, "WIN 104 HSCROLL 7" },
    { 4, WC_TEXT, "WIN 104 TEXT 8" },
    { 5, WC_TEXT, "WIN 104 TEXT 9" },
    { 6, WC_TEXT, "WIN 104 TEXT 10" },
    { 7, WC_GROUPBOX, "WIN 104 GROUPBOX 11" },
    { 8, W_NONE, "DEFINE COLOUR WINDOW P C12" },
    { 9, W_NONE, "DEFINE COLOUR WINDOW P C13" },
    { 10, W_NONE, "DEFINE COLOUR WINDOW P C14" },
    { 11, WC_LISTEDIT, "DEFINE COLOUR WINDOW LISTEDIT 41" },
    { 12, WC_GROUPBOX, "DEFINE COLOUR WINDOW GROUPBOX 44" },
    { 13, WC_TEXT, "DEFINE COLOUR WINDOW TEXT 45" },
    { 14, WC_TEXT, "DEFINE COLOUR WINDOW TEXT 46" },
};

static const DialogCtlEntry g_ctls_105[] = {
    { 1, WC_PUSHBUTTON, "PROFILE WINDOW PUSHBUTTON 37" },
    { 2, WC_PUSHBUTTON, "PROFILE WINDOW PUSHBUTTON 38" },
    { 3, WC_PUSHBUTTON, "PROFILE WINDOW PUSHBUTTON 39" },
    { 4, WC_GROUPBOX, "PROFILE WINDOW GROUPBOX 40" },
    { 5, W_NONE, "PROFILE LINE JOIN" },
    { 6, W_NONE, "PROFILE CURVE JOIN" },
    { 7, W_NONE, "PROFILE SQUARE JOIN" },
    { 8, W_NONE, "PROFILE DELETE POINT" },
    { 9, W_NONE, "PROFILE DELETE ALL" },
    { 10, W_NONE, "PROFILE WINDOW CUSTOM 50" },
    { 11, WC_TEXT, "PROFILE WINDOW TEXT 57" },
    { 12, W_NONE, "PROFILE CURRENT GRAPH" },
    { 13, W_NONE, "PROFILE XPOS" },
    { 14, W_NONE, "PROFILE YPOS" },
    { 15, W_NONE, "PROFILE OPTIONS BUT" },
    { 16, WC_HSCROLL, "PROFILE WINDOW HSCROLL 66" },
};

static const DialogCtlEntry g_ctls_116[] = {
    { 1, WC_PUSHBUTTON, "WIN 116 PUSHBUTTON 37" },
    { 2, WC_PUSHBUTTON, "WIN 116 PUSHBUTTON 38" },
    { 3, WC_PUSHBUTTON, "WIN 116 PUSHBUTTON 39" },
    { 4, WC_GROUPBOX, "WIN 116 GROUPBOX 50" },
    { 5, WC_HSCROLL, "WIN 116 HSCROLL 51" },
    { 6, WC_HSCROLL, "WIN 116 HSCROLL 52" },
    { 7, WC_HSCROLL, "WIN 116 HSCROLL 53" },
    { 8, WC_TEXT, "WIN 116 TEXT 54" },
    { 9, WC_TEXT, "WIN 116 TEXT 55" },
    { 10, WC_TEXT, "WIN 116 TEXT 56" },
    { 11, WC_EDIT, "WIN 116 EDIT 57" },
    { 12, WC_EDIT, "WIN 116 EDIT 58" },
    { 13, WC_EDIT, "WIN 116 EDIT 59" },
    { 14, WC_GROUPBOX, "WIN 116 GROUPBOX 60" },
    { 15, WC_TEXT, "WIN 116 TEXT 61" },
    { 16, WC_TEXT, "WIN 116 TEXT 62" },
    { 17, WC_TEXT, "WIN 116 TEXT 63" },
    { 18, WC_CHECKBOX, "WIN 116 CHECKBOX 68" },
    { 19, WC_HSCROLL, "WIN 116 HSCROLL 73" },
    { 20, WC_HSCROLL, "WIN 116 HSCROLL 74" },
    { 21, WC_HSCROLL, "WIN 116 HSCROLL 75" },
    { 22, WC_EDIT, "WIN 116 EDIT 76" },
    { 23, WC_EDIT, "WIN 116 EDIT 77" },
    { 24, WC_EDIT, "WIN 116 EDIT 78" },
    { 25, W_NONE, "GEOLOGY OPTIONS WINDOW C1" },
    { 26, W_NONE, "GEOLOGY BLOCK VIEW" },
};

static const DialogCtlEntry g_ctls_117[] = {
    { 1, WC_TEXT, "WIN 117 TEXT 34" },
    { 2, WC_TEXT, "WIN 117 TEXT 35" },
    { 3, WC_TEXT, "WIN 117 TEXT 36" },
    { 4, WC_HSCROLL, "WIN 117 HSCROLL 37" },
    { 5, WC_HSCROLL, "WIN 117 HSCROLL 38" },
    { 6, WC_HSCROLL, "WIN 117 HSCROLL 39" },
    { 7, W_NONE, "THREED DECLINATION" },
    { 8, W_NONE, "THREED ELEVATION" },
    { 9, W_NONE, "THREED SCALE" },
    { 10, WC_GROUPBOX, "WIN 117 GROUPBOX 43" },
    { 11, WC_PUSHBUTTON, "WIN 117 PUSHBUTTON 44" },
    { 12, WC_PUSHBUTTON, "WIN 117 PUSHBUTTON 45" },
    { 13, WC_PUSHBUTTON, "WIN 117 PUSHBUTTON 46" },
    { 14, W_NONE, "VIEW OPTIONS PREVIEW" },
    { 15, W_NONE, "VIEW OPTIONS STRAT LIST" },
    { 16, W_NONE, "VIEW OPTIONS ALL SURFACES" },
    { 17, WC_GROUPBOX, "VIEW OPTIONS WINDOW GROUPBOX 107" },
    { 18, WC_TEXT, "VIEW OPTIONS WINDOW TEXT 108" },
    { 19, W_NONE, "VIEW STRAT TYPE LIST" },
    { 20, WC_TEXT, "VIEW OPTIONS WINDOW TEXT 110" },
    { 21, W_NONE, "VIEW BLOCK VIEW OPTIONS" },
};

static const DialogCtlEntry g_ctls_121[] = {
    { 1, W_NONE, "PROJECT OPTIONS WINDOW C3" },
    { 2, W_NONE, "PROJECT OPTIONS OK" },
    { 3, W_NONE, "PROJECT OPTIONS CANCEL" },
    { 4, W_NONE, "PROJECT OPTIONS HELP" },
    { 5, W_NONE, "PROJECT OPTIONS WINDOW C9" },
    { 6, W_NONE, "PROJECT OPTIONS WINDOW C10" },
    { 7, W_NONE, "PROJECT OPTIONS WINDOW C11" },
    { 8, W_NONE, "PROJECT OPTIONS WINDOW C12" },
    { 9, W_NONE, "PROJECT OPTIONS WINDOW C13" },
    { 10, W_NONE, "PROJECT OPTIONS WINDOW C14" },
    { 11, W_NONE, "PROJECT OPTIONS WINDOW C15" },
    { 12, W_NONE, "PROJECT OPTIONS REMOTE" },
    { 13, W_NONE, "PROJECT OPTIONS LOCAL" },
    { 14, WC_TEXT, "PROJECT OPTIONS WINDOW TEXT 99" },
    { 15, WC_TEXT, "PROJECT OPTIONS WINDOW TEXT 100" },
    { 16, W_NONE, "PROJECT OPTIONS PRINT SCALE" },
    { 17, W_NONE, "PROJECT OPTIONS NEW WINDOWS" },
    { 18, W_NONE, "PROJECT OPTIONS GRAVITY" },
    { 19, W_NONE, "PROJECT OPTIONS MAGNETICS" },
    { 20, W_NONE, "PROJECT OPTIONS WINDOW C6a" },
    { 21, WC_GROUPBOX, "PROJECT GEOIMAGE GROUPBOX" },
    { 22, WC_TEXT, "PROJECT OPTIONS WINDOW TEXT 107" },
    { 23, WC_TEXT, "PROJECT OPTIONS WINDOW TEXT 108" },
    { 24, W_NONE, "PROJECT OPTIONS IMAGE SCALE" },
    { 25, W_NONE, "PROJECT MOVIE OPTIONS BUT" },
    { 26, W_NONE, "PROJECT GRV DISP OPTIONS" },
    { 27, W_NONE, "PROJECT WINDOW BACKGROUND" },
    { 28, W_NONE, "PROJECT MAG DISP OPTIONS" },
    { 29, W_NONE, "PROJECT ORIGIN GB" },
    { 30, W_NONE, "PROJECT EASTING" },
    { 31, W_NONE, "PROJECT NORTHING" },
    { 32, W_NONE, "PROJECT EASTING LABEL" },
    { 33, W_NONE, "PROJECT NORTHING LABEL" },
};

static const DialogCtlEntry g_ctls_123[] = {
    { 1, WC_TEXT, "GEOPHYSICS OPTIONS TEXT 1" },
    { 2, WC_TEXT, "GEOPHYSICS OPTIONS TEXT 3" },
    { 3, WC_TEXT, "GEOPHYSICS OPTIONS TEXT 4" },
    { 4, WC_RADIOBUTTON, "WIN 118 RADIOBUTTON 42" },
    { 5, WC_RADIOBUTTON, "WIN 118 RADIOBUTTON 43" },
    { 6, WC_EDIT, "WIN 118 EDIT 48" },
    { 7, WC_EDIT, "WIN 118 EDIT 49" },
    { 8, WC_GROUPBOX, "WIN 118 GROUPBOX 50" },
    { 9, WC_GROUPBOX, "WIN 118 GROUPBOX 51" },
    { 10, W_NONE, "GEOPHYSICS OPTIONS OK" },
    { 11, W_NONE, "GEOPHYSICS OPTIONS CANCEL" },
    { 12, W_NONE, "GEOPHYSICS OPTIONS HELP" },
    { 13, W_NONE, "GEOPHYSICS OPTIONS WIN C1" },
    { 14, W_NONE, "GEOPHYSICS OPTIONS WIN C2" },
    { 15, W_NONE, "GEOPHYSICS OPTIONS WIN C4a" },
    { 16, W_NONE, "GEOPHYSICS OPTIONS WIN C3" },
    { 17, W_NONE, "GEOPHYSICS OPTIONS WIN C4" },
    { 18, W_NONE, "GEOPHYSICS OPTIONS WIN C1a" },
    { 19, W_NONE, "GEOPHYSICS OPTIONS DECL" },
    { 20, W_NONE, "GEOPHYSICS OPTIONS SPATIAL" },
    { 21, W_NONE, "GEOPHYSICS OPTIONS SPECTRAL" },
    { 22, W_NONE, "GEOPHYSICS BOXING CLEVER" },
    { 23, W_NONE, "GEOPHYSICS OPTIONS WIN C2a" },
    { 24, W_NONE, "GEOPHYSICS BOXING CONSTANT" },
    { 25, W_NONE, "GEOPHYSICS OPTIONS WIN C5" },
    { 26, W_NONE, "GEOPHYSICS OPTIONS WIN C6" },
    { 27, W_NONE, "GEOPHYSICS RANGE" },
    { 28, WC_GROUPBOX, "GEOPHYSICS FIELD GROUPBOX" },
    { 29, WC_GROUPBOX, "GEOPHYSICS DEFORM GROUPBOX" },
    { 30, W_NONE, "GEOPHYSICS MAG COMPONENTS" },
    { 31, W_NONE, "GEOPHYSICS BLOCK VIEW" },
    { 32, W_NONE, "GEOPHYSICS CALC RANGE UNIT" },
    { 33, WC_GROUPBOX, "GEOPHYSICS SPECTRAL GROUPBOX" },
    { 34, W_NONE, "GEOPHYSICS PADDING TYPE" },
    { 35, W_NONE, "GEOPHYSICS PADDING PARAM LABEL" },
    { 36, W_NONE, "GEOPHYSICS PADDING PARAM" },
    { 37, W_NONE, "GEOPHYSICS PAD TYPE LABEL" },
    { 38, W_NONE, "GEOPHYSICS RANGE IN CUBES" },
};

static const DialogCtlEntry g_ctls_124[] = {
    { 1, WC_TEXT, "WIN 124 TEXT 1" },
    { 2, WC_TEXT, "WIN 124 TEXT 2" },
    { 3, W_NONE, "JOB PERCENTAGE" },
    { 4, W_NONE, "JOB MESSAGE" },
    { 5, W_NONE, "JOB STATUS CANCEL" },
};

static const DialogCtlEntry g_ctls_125[] = {
    { 1, WC_TEXT, "TOPO OPTIONS WINDOW TEXT 2" },
    { 2, WC_TEXT, "TOPO OPTIONS WINDOW TEXT 3" },
    { 3, WC_TEXT, "TOPO OPTIONS WINDOW TEXT 4" },
    { 4, WC_TEXT, "TOPO OPTIONS WINDOW TEXT 5" },
    { 5, W_NONE, "TOPO OPTIONS SCALE" },
    { 6, W_NONE, "TOPO OPTIONS OFFSET" },
    { 7, W_NONE, "TOPO OPTIONS CONTOUR" },
    { 8, W_NONE, "TOPO OPTIONS INTERVAL" },
    { 9, W_NONE, "TOPO OPTIONS OK" },
    { 10, W_NONE, "TOPO OPTIONS CANCEL" },
    { 11, W_NONE, "TOPO OPTIONS HELP" },
    { 12, W_NONE, "TOPO OPTIONS FULL RANGE" },
    { 13, WC_GROUPBOX, "TOPO OPTIONS WINDOW GROUPBOX 42" },
    { 14, W_NONE, "TOPO OPTIONS ADJ RANGE" },
};

static const DialogCtlEntry g_ctls_126[] = {
    { 1, W_NONE, "DLG ABOUT CANCEL" },
    { 2, WC_TEXT, "DLG 126 TEXT 1" },
    { 3, WC_TEXT, "DLG 126 TEXT 2" },
    { 4, WC_TEXT, "DLG 126 TEXT 3" },
    { 5, WC_TEXT, "DLG 126 TEXT 4" },
    { 6, WC_TEXT, "DLG 126 TEXT 5" },
    { 7, WC_TEXT, "DLG 126 TEXT 7" },
    { 8, WC_TEXT, "DLG 126 TEXT 8" },
    { 9, WC_TEXT, "DLG 126 TEXT 9" },
};

static const DialogCtlEntry g_ctls_127[] = {
    { 1, W_NONE, "PARALLEL OPTIONS ADDRESS" },
    { 2, W_NONE, "PARALLEL OPTIONS LOGIN" },
    { 3, WC_TEXT, "PARALLEL OPTIONS WINDOW TEXT 3" },
    { 4, WC_TEXT, "PARALLEL OPTIONS WINDOW TEXT 4" },
    { 5, W_NONE, "PARALLEL OPTIONS WINDO C1" },
    { 6, W_NONE, "PARALLEL OPTIONS WINDO C2" },
    { 7, W_NONE, "PARALLEL OPTIONS WINDO C3" },
    { 8, W_NONE, "PARALLEL OPTIONS WINDO C4" },
    { 9, W_NONE, "PARALLEL OPTIONS WINDOW PATH" },
    { 10, W_NONE, "PARALLEL OPTIONS PATH" },
};

static const DialogCtlEntry g_ctls_128[] = {
    { 1, W_NONE, "MOVIE FRAMES LABEL" },
    { 2, W_NONE, "MOVIE OPTIONS FRAMES" },
    { 3, W_NONE, "MOVIE SPEED LABEL" },
    { 4, W_NONE, "MOVIE SPEED SCROLL" },
    { 5, W_NONE, "MOVIE SPEED FAST" },
    { 6, W_NONE, "MOVIE SPEED SLOW" },
    { 7, W_NONE, "MOVIE OPTIONS SPEED" },
    { 8, WC_PUSHBUTTON, "MOVIE OPTIONS PUSHBUTTON 38" },
    { 9, WC_PUSHBUTTON, "MOVIE OPTIONS PUSHBUTTON 39" },
    { 10, WC_PUSHBUTTON, "MOVIE OPTIONS PUSHBUTTON 40" },
    { 11, WC_GROUPBOX, "MOVIE OPTIONS GROUPBOX 41" },
    { 12, W_NONE, "MOVIE TYPE" },
    { 13, W_NONE, "MOVIE TYPE LABEL" },
};

static const DialogCtlEntry g_ctls_132[] = {
    { 1, WC_GROUPBOX, "BLOCK CONVERT WINDOW GROUPBOX 1" },
    { 2, W_NONE, "BLOCK CONVERT FLIP X" },
    { 3, W_NONE, "BLOCK CONVERT FLIP Y" },
    { 4, W_NONE, "BLOCK CONVERT FLIP Z" },
    { 5, W_NONE, "BLOCK CONVERT WINDOW OK" },
    { 6, W_NONE, "BLOCK CONVERT WINDOW P C2" },
    { 7, W_NONE, "BLOCK CONVERT WINDOW P C3" },
};

static const DialogCtlEntry g_ctls_133[] = {
    { 1, W_NONE, "XYZ GENERATION WINDOW C1" },
    { 2, W_NONE, "XYZ GENERATION SCROLL PSPACING" },
    { 3, W_NONE, "XYZ GENERATION SCROLL DECL" },
    { 4, WC_TEXT, "XYZ GENERATION WINDOW TEXT 51" },
    { 5, WC_TEXT, "XYZ GENERATION WINDOW TEXT 52" },
    { 6, W_NONE, "XYZ GENERATION PSPACING" },
    { 7, W_NONE, "XYZ GENERATION DECL" },
    { 8, W_NONE, "XYZ GENERATION OK" },
    { 9, W_NONE, "XYZ GENERATION CANCEL" },
    { 10, W_NONE, "XYZ GENERATION HELP" },
    { 11, W_NONE, "XYZ GENERATION WINDOW C5" },
    { 12, WC_TEXT, "XYZ GENERATION WINDOW TEXT 96" },
    { 13, WC_TEXT, "XYZ GENERATION WINDOW TEXT 97" },
    { 14, WC_TEXT, "XYZ GENERATION WINDOW TEXT 98" },
    { 15, W_NONE, "XYZ GENERATION X" },
    { 16, W_NONE, "XYZ GENERATION Z" },
    { 17, W_NONE, "XYZ GENERATION Y" },
    { 18, W_NONE, "XYZ GENERATION SCROLL X" },
    { 19, W_NONE, "XYZ GENERATION SCROLL Y" },
    { 20, W_NONE, "XYZ GENERATION SCROLL Z" },
    { 21, W_NONE, "XYZ GENERATION WINDOW C9" },
    { 22, W_NONE, "XYZ GENERATION SCROLL LLENGTH" },
    { 23, WC_TEXT, "XYZ GENERATION WINDOW TEXT 107" },
    { 24, W_NONE, "XYZ GENERATION LLENGTH" },
    { 25, W_NONE, "XYZ GENERATION SCROLL LSPACING" },
    { 26, WC_TEXT, "XYZ GENERATION WINDOW TEXT 110" },
    { 27, W_NONE, "XYZ GENERATION LSPACING" },
    { 28, W_NONE, "XYZ GENERATION SCROLL LHEIGHT" },
    { 29, WC_TEXT, "XYZ GENERATION WINDOW TEXT 114" },
    { 30, W_NONE, "XYZ GENERATION LHEIGHT" },
    { 31, W_NONE, "XYZ GENERATION WINDOW C2" },
    { 32, W_NONE, "XYZ GENERATION WINDOW C1a" },
    { 33, W_NONE, "XYZ GENERATION WINDOW C2a" },
    { 34, W_NONE, "XYZ GENERATION WINDOW C3" },
};

static const DialogCtlEntry g_ctls_134[] = {
    { 1, W_NONE, "XYZ CONVERT PREVIEW" },
    { 2, W_NONE, "XYZ CONVERT GB" },
    { 3, W_NONE, "XYZ CONVERT OK" },
    { 4, W_NONE, "XYZ CONVERT CANCEL" },
    { 5, W_NONE, "XYZ CONVERT HELP" },
    { 6, WC_TEXT, "XYZ CONVERT WINDOW TEXT 93" },
    { 7, WC_TEXT, "XYZ CONVERT WINDOW TEXT 94" },
    { 8, WC_TEXT, "XYZ CONVERT WINDOW TEXT 95" },
    { 9, WC_TEXT, "XYZ CONVERT WINDOW TEXT 96" },
    { 10, WC_TEXT, "XYZ CONVERT WINDOW TEXT 97" },
    { 11, WC_TEXT, "XYZ CONVERT WINDOW TEXT 98" },
    { 12, W_NONE, "XYZ CONVERT XCOLUMN" },
    { 13, W_NONE, "XYZ CONVERT YCOLUMN" },
    { 14, W_NONE, "XYZ CONVERT ZCOLUMN" },
    { 15, W_NONE, "XYZ CONVERT XOFFSET" },
    { 16, W_NONE, "XYZ CONVERT YOFFSET" },
    { 17, W_NONE, "XYZ CONVERT ZOFFSET" },
};

static const DialogCtlEntry g_ctls_135[] = {
    { 1, WC_PUSHBUTTON, "ROCK DATABASE WIN PUSHBUTTON 38" },
    { 2, WC_GROUPBOX, "ROCK DATABASE WIN GROUPBOX 1" },
    { 3, WC_LBOX, "ROCK DATABASE WIN LBOX 2" },
    { 4, W_NONE, "ROCK DATABASE IMPORT" },
    { 5, W_NONE, "ROCK DATABASE EXPORT" },
    { 6, W_NONE, "ROCK DATABASE NEW" },
    { 7, W_NONE, "ROCK DATABASE DELETE" },
    { 8, WC_EDIT, "ROCK DATABASE EDIT" },
    { 9, WC_PUSHBUTTON, "ROCK DATABASE WIN PUSHBUTTON 39" },
    { 10, WC_PUSHBUTTON, "ROCK DATABASE WIN PUSHBUTTON 40" },
};

static const DialogCtlEntry g_ctls_136[] = {
    { 1, WC_GROUPBOX, "PROFILE OPTION WINDOW GROUPBOX 1" },
    { 2, W_NONE, "PROFILE OPTION WINDOW C2" },
    { 3, W_NONE, "PROFILE OPTION WINDOW C3" },
    { 4, W_NONE, "PROFILE OPTION WINDOW C4" },
    { 5, WC_HSCROLL, "PROFILE OPTION WINDOW HSCROLL 65" },
    { 6, WC_EDIT, "PROFILE OPTION WINDOW EDIT 66" },
    { 7, WC_TEXT, "PROFILE OPTION WINDOW TEXT 67" },
    { 8, WC_TEXT, "PROFILE OPTION WINDOW TEXT 68" },
    { 9, WC_TEXT, "PROFILE OPTION WINDOW TEXT 69" },
    { 10, WC_TEXT, "PROFILE OPTION WINDOW TEXT 70" },
    { 11, WC_TEXT, "PROFILE OPTION WINDOW TEXT 71" },
    { 12, W_NONE, "PROFILE OPTION MIN SCALE" },
    { 13, W_NONE, "PROFILE OPTION MAX SCALE" },
    { 14, W_NONE, "PROFILE OPTION MIN REPLACE" },
    { 15, W_NONE, "PROFILE OPTION MAX REPLACE" },
    { 16, WC_TEXT, "PROFILE OPTION WINDOW TEXT 76" },
    { 17, W_NONE, "PROFILE OPTION ALTDIST" },
};

static const DialogCtlEntry g_ctls_137[] = {
    { 1, W_NONE, "EVENT OK" },
    { 2, W_NONE, "EVENT NAME" },
    { 3, W_NONE, "EVENT NAME GB" },
    { 4, W_NONE, "EVENT CANCEL" },
    { 5, W_NONE, "EVENT HELP" },
    { 6, W_NONE, "EVENT PREVIEW" },
    { 7, W_NONE, "EVENT OPTION SELECTION" },
    { 8, W_NONE, "EVENT PREVIOUS" },
    { 9, W_NONE, "EVENT NEXT" },
};

static const DialogCtlEntry g_ctls_138[] = {
    { 1, W_NONE, "PREVIEW TYPE OPTIONS" },
    { 2, W_NONE, "PREVIEW TYPE" },
    { 3, W_NONE, "PREVIEW UPDATE" },
};

static const DialogCtlEntry g_ctls_139[] = {
    { 1, W_NONE, "XYZ GB" },
    { 2, WC_TEXT, "XYZ X TEXT" },
    { 3, WC_TEXT, "XYZ Y TEXT" },
    { 4, WC_TEXT, "XYZ Z TEXT" },
    { 5, W_NONE, "XYZ X" },
    { 6, W_NONE, "XYZ Z" },
    { 7, W_NONE, "XYZ Y" },
    { 8, W_NONE, "XYZ X BAR" },
    { 9, W_NONE, "XYZ Y BAR" },
    { 10, W_NONE, "XYZ Z BAR" },
};

static const DialogCtlEntry g_ctls_140[] = {
    { 1, WC_GROUPBOX, "WIN 140 GROUPBOX 42" },
    { 2, W_NONE, "DDP DDIR BAR" },
    { 3, W_NONE, "DDP DIP BAR" },
    { 4, W_NONE, "DDP PITCH BAR" },
    { 5, WC_TEXT, "WIN 140 TEXT 46" },
    { 6, WC_TEXT, "WIN 140 TEXT 47" },
    { 7, W_NONE, "DDP PITCH LABEL" },
    { 8, W_NONE, "DDP DDIR" },
    { 9, W_NONE, "DDP PITCH" },
    { 10, W_NONE, "DDP DIP" },
};

static const DialogCtlEntry g_ctls_141[] = {
    { 1, WC_GROUPBOX, "ROTATION WINDOW GROUPBOX" },
    { 2, W_NONE, "ROTATION ROT BAR" },
    { 3, W_NONE, "ROTATION ROT LABEL" },
    { 4, W_NONE, "ROTATION ROT" },
    { 5, WC_TEXT, "ROTATION WINDOW TEXT 51" },
};

static const DialogCtlEntry g_ctls_142[] = {
    { 1, WC_GROUPBOX, "PP GROUPBOX" },
    { 2, W_NONE, "PP PDIR BAR" },
    { 3, W_NONE, "PP PLUNGE BAR" },
    { 4, W_NONE, "PP PDIR LABEL" },
    { 5, W_NONE, "PP PLUNGE LABEL" },
    { 6, W_NONE, "PP PDIR" },
    { 7, W_NONE, "PP PLUNGE" },
};

static const DialogCtlEntry g_ctls_143[] = {
    { 1, W_NONE, "GMA GEOMETRY" },
    { 2, W_NONE, "GMA GEOMETRY LABEL" },
    { 3, WC_GROUPBOX, "GMA GROUPBOX" },
    { 4, W_NONE, "GMA MOVEMENT" },
    { 5, W_NONE, "GMA MOVEMENT LABEL" },
    { 6, W_NONE, "GMA ALTERATION" },
    { 7, W_NONE, "GMA ALTERATION LABEL" },
    { 8, WC_EDIT, "GMA ALTERATION EDIT" },
    { 9, W_NONE, "GMA COLOR BUTTON" },
    { 10, W_NONE, "GMA PROFILE BUTTON" },
};

static const DialogCtlEntry g_ctls_144[] = {
    { 1, W_NONE, "ALT ALTERATION" },
    { 2, W_NONE, "ALT ALTERATION LABEL" },
    { 3, WC_EDIT, "ALT ALTERATION EDIT" },
    { 4, WC_GROUPBOX, "ALT GROUPBOX" },
};

static const DialogCtlEntry g_ctls_145[] = {
    { 1, WC_GROUPBOX, "DDD GROUPBOX" },
    { 2, W_NONE, "DDD DDIR BAR" },
    { 3, W_NONE, "DDD DIP BAR" },
    { 4, W_NONE, "DDD DDIR LABEL" },
    { 5, W_NONE, "DDD DIP LABEL" },
    { 6, W_NONE, "DDD DDIR" },
    { 7, W_NONE, "DDD DIP" },
};

static const DialogCtlEntry g_ctls_146[] = {
    { 1, W_NONE, "MATRIX TOP LEFT" },
    { 2, W_NONE, "MATRIX TOP CENTER" },
    { 3, W_NONE, "MATRIX TOP RIGHT" },
    { 4, W_NONE, "MATRIX CENTER LEFT" },
    { 5, W_NONE, "MATRIX CENTER CENTER" },
    { 6, W_NONE, "MATRIX CENTER RIGHT" },
    { 7, W_NONE, "MATRIX BOTTOM LEFT" },
    { 8, W_NONE, "MATRIX BOTTOM CENTER" },
    { 9, W_NONE, "MATRIX BOTTOM RIGHT" },
    { 10, WC_GROUPBOX, "MATRIX GROUPBOX" },
};

static const DialogCtlEntry g_ctls_148[] = {
    { 1, W_NONE, "ROCK HEIGHT" },
    { 2, W_NONE, "ROCK HEIGHT LABEL" },
    { 3, W_NONE, "ROCK DENSITY" },
    { 4, W_NONE, "ROCK DENSITY LABEL" },
    { 5, W_NONE, "ROCK NAME LABEL" },
    { 6, W_NONE, "ROCK INTENSITY" },
    { 7, W_NONE, "ROCK COLOR" },
    { 8, WC_GROUPBOX, "ROCK WINDOW GROUPBOX 18" },
    { 9, W_NONE, "ROCK INTENSITY LABEL" },
    { 10, WC_GROUPBOX, "ROCK WINDOW GROUPBOX 50" },
    { 11, W_NONE, "ROCK ANISOTROPY" },
    { 12, W_NONE, "ROCK REMANENCE" },
    { 13, W_NONE, "ROCK DECLINATION LABEL" },
    { 14, W_NONE, "ROCK INCLINATION LABEL" },
    { 15, W_NONE, "ROCK X" },
    { 16, WC_TEXT, "ROCK WINDOW TEXT 56" },
    { 17, W_NONE, "ROCK Y" },
    { 18, W_NONE, "ROCK Z" },
    { 19, W_NONE, "ROCK X LABEL" },
    { 20, W_NONE, "ROCK Y LABEL" },
    { 21, W_NONE, "ROCK Z LABEL" },
    { 22, W_NONE, "ROCK DECLINATION" },
    { 23, W_NONE, "ROCK INCLINATION" },
    { 24, WC_GROUPBOX, "ROCK REMANENCE GROUPBOX" },
    { 25, W_NONE, "ROCK DIP" },
    { 26, W_NONE, "ROCK DDIR" },
    { 27, W_NONE, "ROCK PITCH" },
    { 28, W_NONE, "ROCK DIP LABEL" },
    { 29, W_NONE, "ROCK DDIR LABEL" },
    { 30, W_NONE, "ROCK PITCH LABEL" },
    { 31, W_NONE, "ROCK NAME" },
    { 32, WC_GROUPBOX, "ROCK WINDOW GROUPBOX 72" },
    { 33, W_NONE, "ROCK OK" },
    { 34, W_NONE, "ROCK CANCEL" },
    { 35, W_NONE, "ROCK HELP" },
    { 36, W_NONE, "ROCK ALTER" },
    { 37, W_NONE, "ROCK WIDTH LABEL" },
    { 38, W_NONE, "ROCK WIDTH" },
};

static const DialogCtlEntry g_ctls_152[] = {
    { 1, W_NONE, "FFORM PROFILE" },
    { 2, W_NONE, "FFORM TYPE LABEL" },
    { 3, W_NONE, "FFORM TYPE" },
    { 4, WC_GROUPBOX, "FFORM GROUPBOX" },
    { 5, W_NONE, "FFORM SINGLE" },
};

static const DialogCtlEntry g_ctls_153[] = {
    { 1, WC_GROUPBOX, "FDSCL GROUPBOX" },
    { 2, W_NONE, "FDSCL WAVE BAR" },
    { 3, W_NONE, "FDSCL AMPLITUDE BAR" },
    { 4, W_NONE, "FDSCL CYCL BAR" },
    { 5, W_NONE, "FDSCL WAVE LABEL" },
    { 6, W_NONE, "FDSCL AMPLITUDE LABEL" },
    { 7, W_NONE, "FDSCL CYCL LABEL" },
    { 8, W_NONE, "FDSCL WAVE" },
    { 9, W_NONE, "FDSCL CYCL" },
    { 10, W_NONE, "FDSCL AMPLITUDE" },
};

static const DialogCtlEntry g_ctls_154[] = {
    { 1, W_NONE, "TGMA GEOMETRY" },
    { 2, W_NONE, "TGMA GEOMETRY LABEL" },
    { 3, WC_GROUPBOX, "WIN 154 GROUPBOX 93" },
    { 4, W_NONE, "TGMA MOVEMENT" },
    { 5, W_NONE, "TGMA MOVEMENT LABEL" },
    { 6, W_NONE, "TGMA ALTERATION" },
    { 7, W_NONE, "TGMA ALTERATION LABEL" },
    { 8, WC_EDIT, "TGMA ALTERATION EDIT" },
    { 9, W_NONE, "TGMA TYPE LABEL" },
    { 10, W_NONE, "TGMA TYPE" },
    { 11, W_NONE, "TGMA PROFILE BUTTON" },
};

static const DialogCtlEntry g_ctls_155[] = {
    { 1, W_NONE, "FSCL SLIP BAR" },
    { 2, W_NONE, "FSCL SLIP LABEL" },
    { 3, W_NONE, "FSCL SLIP" },
    { 4, WC_GROUPBOX, "FSCL GROUPBOX" },
    { 5, W_NONE, "FSCL ROTATION BAR" },
    { 6, W_NONE, "FSCL ROTATION LABEL" },
    { 7, W_NONE, "FSCL ROTATION" },
    { 8, W_NONE, "FSCL AMPLITUDE BAR" },
    { 9, W_NONE, "FSCL AMPLITUDE LABEL" },
    { 10, W_NONE, "FSCL AMPLITUDE" },
    { 11, W_NONE, "FSCL RADIUS BAR" },
    { 12, W_NONE, "FSCL RADIUS LABEL" },
    { 13, W_NONE, "FSCL RADIUS" },
    { 14, W_NONE, "FSCL CYL BAR" },
    { 15, W_NONE, "FSCL CYL LABEL" },
    { 16, W_NONE, "FSCL CYL" },
    { 17, W_NONE, "FSCL PP BAR" },
    { 18, W_NONE, "FSCL PP LABEL" },
    { 19, W_NONE, "FSCL PP" },
};

static const DialogCtlEntry g_ctls_156[] = {
    { 1, W_NONE, "SSCL SLIP BAR" },
    { 2, W_NONE, "SSCL SLIP LABEL" },
    { 3, W_NONE, "SSCL SLIP" },
    { 4, WC_GROUPBOX, "SSCL WINDOW GROUPBOX 54" },
    { 5, W_NONE, "SSCL ROTATION BAR" },
    { 6, W_NONE, "SSCL ROTATION LABEL" },
    { 7, W_NONE, "SSCL ROTATION" },
    { 8, W_NONE, "SSCL AMPLITUDE BAR" },
    { 9, W_NONE, "SSCL AMPLITUDE LABEL" },
    { 10, W_NONE, "SSCL AMPLITUDE" },
    { 11, W_NONE, "SSCL RADIUS BAR" },
    { 12, W_NONE, "SSCL RADIUS LABEL" },
    { 13, W_NONE, "SSCL RADIUS" },
    { 14, W_NONE, "SSCL CYL BAR" },
    { 15, W_NONE, "SSCL CYL LABEL" },
    { 16, W_NONE, "SSCL CYL" },
    { 17, W_NONE, "SSCL PP BAR" },
    { 18, W_NONE, "SSCL PP LABEL" },
    { 19, W_NONE, "SSCL PP" },
    { 20, W_NONE, "SSCL WIDTH BAR" },
    { 21, W_NONE, "SSCL WIDTH LABEL" },
    { 22, W_NONE, "SSCL WIDTH" },
};

static const DialogCtlEntry g_ctls_157[] = {
    { 1, W_NONE, "FDYKE MERGE" },
    { 2, W_NONE, "FDYKE TYPE LABEL" },
    { 3, W_NONE, "FDYKE TYPE" },
    { 4, WC_GROUPBOX, "FDYKE GROUPBOX" },
    { 5, W_NONE, "FDYKE ALTERATION" },
    { 6, W_NONE, "FDYKE ALTERATION LABEL" },
    { 7, WC_EDIT, "FDYKE ALTERATION EDIT" },
    { 8, W_NONE, "FDYKE PROP BUTTON" },
};

static const DialogCtlEntry g_ctls_158[] = {
    { 1, WC_GROUPBOX, "SW GROUPBOX" },
    { 2, W_NONE, "SW SLIP BAR" },
    { 3, W_NONE, "SW WIDTH BAR" },
    { 4, W_NONE, "SW SLIP LABEL" },
    { 5, W_NONE, "SW WIDTH LABEL" },
    { 6, W_NONE, "SW SLIP" },
    { 7, W_NONE, "SW WIDTH" },
};

static const DialogCtlEntry g_ctls_159[] = {
    { 1, W_NONE, "FPLUG MERGE" },
    { 2, W_NONE, "FPLUG GEOMETRY LABEL" },
    { 3, W_NONE, "FPLUG GEOMETRY" },
    { 4, WC_GROUPBOX, "FPLUG GROUPBOX" },
    { 5, W_NONE, "FPLUG ALTERATION" },
    { 6, W_NONE, "FPLUG ALTERATION LABEL" },
    { 7, WC_EDIT, "FPLUG ALTERATION EDIT" },
    { 8, W_NONE, "FPLUG PROP BUTTON" },
};

static const DialogCtlEntry g_ctls_160[] = {
    { 1, WC_GROUPBOX, "PSCL GROUPBOX" },
    { 2, W_NONE, "PSCL RADIUS BAR" },
    { 3, W_NONE, "PSCL ANGLE BAR" },
    { 4, W_NONE, "PSCL RADIUS LABEL" },
    { 5, W_NONE, "PSCL ANGLE LABEL" },
    { 6, W_NONE, "PSCL RADIUS" },
    { 7, W_NONE, "PSCL ANGLE" },
    { 8, W_NONE, "PSCL BVALUE BAR" },
    { 9, W_NONE, "PSCL BVALUE LABEL" },
    { 10, W_NONE, "PSCL BVALUE" },
};

static const DialogCtlEntry g_ctls_161[] = {
    { 1, WC_GROUPBOX, "AXIS GROUPBOX" },
    { 2, W_NONE, "AXIS X BAR" },
    { 3, W_NONE, "AXIS Y BAR" },
    { 4, W_NONE, "AXIS Z BAR" },
    { 5, W_NONE, "AXIS X LABEL" },
    { 6, W_NONE, "AXIS Y LABEL" },
    { 7, W_NONE, "AXIS Z LABEL" },
    { 8, W_NONE, "AXIS X" },
    { 9, W_NONE, "AXIS Z" },
    { 10, W_NONE, "AXIS Y" },
};

static const DialogCtlEntry g_ctls_162[] = {
    { 1, WC_GROUPBOX, "CORNER GROUPBOX" },
    { 2, W_NONE, "CORNER CENTER" },
    { 3, W_NONE, "CORNER SWUPPER" },
    { 4, W_NONE, "CORNER IMPORT FILE" },
};

static const DialogCtlEntry g_ctls_163[] = {
    { 1, W_NONE, "IPROP GOURPBOX" },
    { 2, W_NONE, "IPROP PROPERTIES" },
    { 3, W_NONE, "IPROP TRANSPARENT LABEL" },
    { 4, W_NONE, "IPROP TRANSPARENT" },
};

static const DialogCtlEntry g_ctls_164[] = {
    { 1, WC_GROUPBOX, "ISCL GROUPBOX" },
    { 2, W_NONE, "ISCL BSIZE" },
    { 3, W_NONE, "ISCL BSIZE BAR" },
    { 4, W_NONE, "ISCL BSIZE LABEL" },
};

static const DialogCtlEntry g_ctls_165[] = {
    { 1, W_NONE, "SURFACE VIEW" },
    { 2, W_NONE, "SURFACE TYPE LIST" },
    { 3, W_NONE, "SURFACE GORUPBOX" },
    { 4, W_NONE, "SURFACE XDIM LABEL" },
    { 5, W_NONE, "SURFACE XDIM BAR" },
    { 6, W_NONE, "SURFACE XDIM" },
    { 7, W_NONE, "SURFACE YDIM LABEL" },
    { 8, W_NONE, "SURFACE YDIM BAR" },
    { 9, W_NONE, "SURFACE YDIM" },
    { 10, W_NONE, "SURFACE ZDIM LABEL" },
    { 11, W_NONE, "SURFACE ZDIM BAR" },
    { 12, W_NONE, "SURFACE ZDIM" },
};

static const DialogCtlEntry g_ctls_166[] = {
    { 1, W_NONE, "FOLD TRACE ADD POINT" },
    { 2, W_NONE, "FOLD TRACE DELETE POINT" },
    { 3, W_NONE, "FOLD TRACE OK" },
    { 4, W_NONE, "FOLD TRACE CANCEL" },
    { 5, W_NONE, "FOLD TRACE HELP" },
    { 6, WC_GROUPBOX, "FOLD TRACE GROUPBOX" },
    { 7, WC_GROUPBOX, "FOLD TRACE REF GROUPBOX" },
    { 8, W_NONE, "FOLD TRACE XTOP LABEL" },
    { 9, W_NONE, "FOLD TRACE YTOP LABEL" },
    { 10, W_NONE, "FOLD TRACE ZTOP LABEL" },
    { 11, W_NONE, "FOLD TRACE XTOP" },
    { 12, W_NONE, "FOLD TRACE ZTOP" },
    { 13, W_NONE, "FOLD TRACE YTOP" },
    { 14, W_NONE, "FOLD TRACE XTOP BAR" },
    { 15, W_NONE, "FOLD TRACE YTOP BAR" },
    { 16, W_NONE, "FOLD TRACE ZTOP BAR" },
    { 17, W_NONE, "FOLD TRACE XBOT LABEL" },
    { 18, W_NONE, "FOLD TRACE YBOT LABEL" },
    { 19, W_NONE, "FOLD TRACE ZBOT LABEL" },
    { 20, W_NONE, "FOLD TRACE XBOT" },
    { 21, W_NONE, "FOLD TRACE ZBOT" },
    { 22, W_NONE, "FOLD TRACE YBOT" },
    { 23, W_NONE, "FOLD TRACE XBOT BAR" },
    { 24, W_NONE, "FOLD TRACE YBOT BAR" },
    { 25, W_NONE, "FOLD TRACE ZBOT BAR" },
    { 26, W_NONE, "FOLD TRACE TOP LABEL" },
    { 27, W_NONE, "FOLD TRACE BOTTOM LABEL" },
};

static const DialogCtlEntry g_ctls_167[] = {
    { 1, W_NONE, "FAULT TRACE OK" },
    { 2, W_NONE, "FAULT TRACE CANCEL" },
    { 3, W_NONE, "FAULT TRACE HELP" },
    { 4, WC_GROUPBOX, "FAULT TRACE WINDOW GROUPBOX 44" },
    { 5, W_NONE, "FAULT TRACE XTOP LABEL" },
    { 6, W_NONE, "FAULT TRACE YTOP LABEL" },
    { 7, W_NONE, "FAULT TRACE ZTOP LABEL" },
    { 8, W_NONE, "FAULT TRACE XTOP" },
    { 9, W_NONE, "FAULT TRACE ZTOP" },
    { 10, W_NONE, "FAULT TRACE YTOP" },
    { 11, W_NONE, "FAULT TRACE XTOP BAR" },
    { 12, W_NONE, "FAULT TRACE YTOP BAR" },
    { 13, W_NONE, "FAULT TRACE ZTOP BAR" },
    { 14, W_NONE, "FAULT TRACE XBOT LABEL" },
    { 15, W_NONE, "FAULT TRACE YBOT LABEL" },
    { 16, W_NONE, "FAULT TRACE ZBOT LABEL" },
    { 17, W_NONE, "FAULT TRACE XBOT" },
    { 18, W_NONE, "FAULT TRACE ZBOT" },
    { 19, W_NONE, "FAULT TRACE YBOT" },
    { 20, W_NONE, "FAULT TRACE XBOT BAR" },
    { 21, W_NONE, "FAULT TRACE YBOT BAR" },
    { 22, W_NONE, "FAULT TRACE ZBOT BAR" },
    { 23, W_NONE, "FAULT TRACE TOP LABEL" },
    { 24, W_NONE, "FAULT TRACE BOT LABEL" },
};

static const DialogCtlEntry g_ctls_168[] = {
    { 1, W_NONE, "TRACE BUTTON" },
};

static const DialogCtlEntry g_ctls_169[] = {
    { 1, W_NONE, "STRATIGRAPHY LIST" },
    { 2, W_NONE, "STRATIGRAPHY NEW" },
    { 3, W_NONE, "STRATIGRAPHY DELETE" },
    { 4, WC_EDIT, "STRATIGRAPHY EDIT" },
    { 5, W_NONE, "STRATIGRAPHY UP" },
    { 6, W_NONE, "STRATIGRAPHY DOWN" },
    { 7, W_NONE, "STRATIGRAPHY LABEL" },
};

static const DialogCtlEntry g_ctls_170[] = {
    { 1, W_NONE, "GENERIC LABEL 1" },
    { 2, W_NONE, "GENERIC LABEL 2" },
    { 3, W_NONE, "GENERIC LABEL 3" },
    { 4, W_NONE, "GENERIC LABEL 4" },
    { 5, W_NONE, "GENERIC LABEL 5" },
    { 6, W_NONE, "GENERIC LABEL 6" },
    { 7, W_NONE, "GENERIC LABEL 7" },
    { 8, W_NONE, "GENERIC LABEL 8" },
    { 9, W_NONE, "GENERIC LABEL 9" },
    { 10, W_NONE, "GENERIC LABEL 10" },
    { 11, W_NONE, "GENERIC 1" },
    { 12, W_NONE, "GENERIC 2" },
    { 13, W_NONE, "GENERIC 3" },
    { 14, W_NONE, "GENERIC 4" },
    { 15, W_NONE, "GENERIC 5" },
    { 16, W_NONE, "GENERIC 6" },
    { 17, W_NONE, "GENERIC 7" },
    { 18, W_NONE, "GENERIC 8" },
    { 19, W_NONE, "GENERIC 9" },
    { 20, W_NONE, "GENERIC 10" },
};

static const DialogCtlEntry g_ctls_171[] = {
    { 1, WC_GROUPBOX, "TIME GROUPBOX" },
    { 2, W_NONE, "TIME LENGTH LABEL" },
    { 3, W_NONE, "TIME LENGTH" },
    { 4, W_NONE, "TIME LENGTH BAR" },
};

static const DialogCtlEntry g_ctls_172[] = {
    { 1, W_NONE, "PREVIEW MENU VIEW1" },
    { 2, W_NONE, "PREVIEW MENU VIEW2" },
    { 3, W_NONE, "PREVIEW MENU VIEW3" },
};

static const DialogCtlEntry g_ctls_173[] = {
    { 1, W_NONE, "LICENCE WARNING LABEL" },
    { 2, W_NONE, "LICENCE PROMPT LABEL" },
    { 3, W_NONE, "LICENCE COMPANY LABEL" },
    { 4, W_NONE, "LICENCE CODE LABEL" },
    { 5, WC_GROUPBOX, "LICENCE GROUPBOX" },
    { 6, W_NONE, "LICENCE COMPANY" },
    { 7, W_NONE, "LICENCE CODE" },
    { 8, WC_PUSHBUTTON, "LICENCE WINDOW PUSHBUTTON 38" },
    { 9, WC_PUSHBUTTON, "LICENCE WINDOW PUSHBUTTON 39" },
    { 10, WC_PUSHBUTTON, "LICENCE WINDOW PUSHBUTTON 40" },
    { 11, W_NONE, "LICENCE REQUEST" },
    { 12, W_NONE, "LICENCE IMPORT BUTTON" },
};

static const DialogCtlEntry g_ctls_174[] = {
    { 1, W_NONE, "IMAGE RANGE MAX LABEL" },
    { 2, W_NONE, "IMAGE RANGE MIN LABEL" },
    { 3, W_NONE, "IMAGE RANGE MAX" },
    { 4, W_NONE, "IMAGE RANGE MIN" },
    { 5, W_NONE, "IMAGE RANGE MAX BAR" },
    { 6, W_NONE, "IMAGE RANGE MIN BAR" },
    { 7, WC_GROUPBOX, "IMAGE CLIPPING GROUPBOX" },
    { 8, W_NONE, "IMAGE OPTION MAXCLIP UNIT" },
    { 9, W_NONE, "IMAGE OPTION MINCLIP UNIT" },
    { 10, W_NONE, "IMAGE RANGE LABEL" },
    { 11, WC_GROUPBOX, "IMAGE LUT GROUPBOX" },
    { 12, W_NONE, "IMAGE OPTION WINDOW PU C3" },
    { 13, W_NONE, "IMAGE OPTION WINDOW PU C4" },
    { 14, W_NONE, "IMAGE OPTION WINDOW PU C5" },
    { 15, W_NONE, "IMAGE LUT GREY" },
    { 16, W_NONE, "IMAGE LUT PSEUDO" },
    { 17, W_NONE, "IMAGE LUT CONTOUR" },
    { 18, W_NONE, "IMAGE NUM CONTOUR" },
    { 19, W_NONE, "IMAGE NUM CONTOUR LABEL" },
    { 20, W_NONE, "IMAGE CLIPPING TYPE" },
    { 21, W_NONE, "IMAGE GRID" },
    { 22, WC_GROUPBOX, "IMAGE GRID GROUPBOX" },
    { 23, W_NONE, "IMAGE GRID XSTART LABEL" },
    { 24, W_NONE, "IMAGE GRID YSTART LABEL" },
    { 25, W_NONE, "IMAGE GRID XINC LABEL" },
    { 26, W_NONE, "IMAGE GRID YINC LABEL" },
    { 27, W_NONE, "IMAGE GRID XSTART" },
    { 28, W_NONE, "IMAGE GRID YSTART" },
    { 29, W_NONE, "IMAGE GRID XINC" },
    { 30, W_NONE, "IMAGE GRID YINC" },
    { 31, W_NONE, "IMAGE GRID AUTO" },
    { 32, W_NONE, "IMAGE GRID SENSOR" },
};

static const DialogCtlEntry g_ctls_175[] = {
    { 1, W_NONE, "CONTACT STEP 2" },
    { 2, WC_TEXT, "CONTACT WINDOW TEXT 46" },
    { 3, WC_TEXT, "CONTACT WINDOW TEXT 47" },
    { 4, WC_TEXT, "CONTACT WINDOW TEXT 48" },
    { 5, WC_TEXT, "CONTACT WINDOW TEXT 49" },
    { 6, WC_TEXT, "CONTACT WINDOW TEXT 50" },
    { 7, WC_TEXT, "CONTACT WINDOW TEXT 51" },
    { 8, WC_TEXT, "CONTACT WINDOW TEXT 52" },
    { 9, WC_TEXT, "CONTACT WINDOW TEXT 53" },
    { 10, WC_TEXT, "CONTACT WINDOW TEXT 54" },
    { 11, WC_PUSHBUTTON, "CONTACT WINDOW PUSHBUTTON 56" },
    { 12, WC_PUSHBUTTON, "CONTACT WINDOW PUSHBUTTON 57" },
    { 13, WC_PUSHBUTTON, "CONTACT WINDOW PUSHBUTTON 58" },
    { 14, W_NONE, "CONTACT STEP 1" },
    { 15, W_NONE, "CONTACT STEP 3" },
    { 16, W_NONE, "CONTACT STEP 4" },
    { 17, WC_TEXT, "CONTACT WINDOW TEXT 62" },
    { 18, WC_TEXT, "CONTACT WINDOW TEXT 63" },
    { 19, WC_PUSHBUTTON, "CONTACT WINDOW PUSHBUTTON 64" },
    { 20, WC_TEXT, "CONTACT WINDOW TEXT 65" },
    { 21, WC_TEXT, "CONTACT WINDOW TEXT 66" },
    { 22, WC_TEXT, "CONTACT WINDOW TEXT 67" },
    { 23, WC_TEXT, "CONTACT WINDOW TEXT 68" },
    { 24, WC_TEXT, "CONTACT WINDOW TEXT 69" },
    { 25, WC_TEXT, "CONTACT WINDOW TEXT 70" },
    { 26, W_NONE, "CONTACT STEP 5" },
    { 27, WC_TEXT, "CONTACT WINDOW TEXT 72" },
    { 28, WC_TEXT, "CONTACT WINDOW TEXT 73" },
};

static const DialogCtlEntry g_ctls_176[] = {
    { 1, W_NONE, "VIEW PREVIEW" },
    { 2, WC_GROUPBOX, "VIEW DIM GROUPBOX" },
    { 3, W_NONE, "DIM X BAR" },
    { 4, W_NONE, "DIM Y BAR" },
    { 5, W_NONE, "DIM Z BAR" },
    { 6, WC_TEXT, "DIM X TEXT" },
    { 7, WC_TEXT, "DIM Y TEXT" },
    { 8, WC_TEXT, "DIM Z TEXT" },
    { 9, W_NONE, "DIM X" },
    { 10, W_NONE, "DIM Z" },
    { 11, W_NONE, "DIM Y" },
    { 12, WC_GROUPBOX, "VIEW ORIGIN GROUPBOX" },
    { 13, W_NONE, "VIEW ORIGIN X BAR" },
    { 14, W_NONE, "VIEW ORIGIN Y BAR" },
    { 15, W_NONE, "VIEW ORIGIN Z BAR" },
    { 16, WC_TEXT, "VIEW ORIGIN X TEXT" },
    { 17, WC_TEXT, "VIEW ORIGIN Y TEXT" },
    { 18, WC_TEXT, "VIEW ORIGIN Z TEXT" },
    { 19, W_NONE, "VIEW ORIGIN X" },
    { 20, W_NONE, "VIEW ORIGIN Z" },
    { 21, W_NONE, "VIEW ORIGIN Y" },
    { 22, W_NONE, "VIEW OK" },
    { 23, W_NONE, "VIEW CANCEL" },
    { 24, W_NONE, "VIEW HELP" },
    { 25, W_NONE, "VIEW NEW" },
    { 26, W_NONE, "VIEW DELETE" },
    { 27, WC_GROUPBOX, "VIEW LIST GROUPBOX" },
    { 28, W_NONE, "VIEW CURRENT LIST" },
    { 29, WC_TEXT, "VIEW CURRENT TEXT" },
    { 30, WC_GROUPBOX, "VIEW CUBE SIZE GROUPBOX" },
    { 31, W_NONE, "VIEW GEOLOGY CUBE" },
    { 32, W_NONE, "VIEW GEOPHYSICS CUBE" },
    { 33, W_NONE, "VIEW GEOLOGY CUBE LABEL" },
    { 34, W_NONE, "VIEW GEOPHYSICS CUBE LABEL" },
    { 35, W_NONE, "VIEW CUBE SIZE UNIT" },
    { 36, W_NONE, "VIEW CUBE UNIT" },
    { 37, W_NONE, "VIEW 3D OPTIONS BUTTON" },
};

static const DialogCtlEntry g_ctls_177[] = {
    { 1, W_NONE, "LAYER DISPLAY LIST" },
    { 2, W_NONE, "LAYER DISPLAY TYPE" },
    { 3, W_NONE, "LAYER RESET COLORS" },
    { 4, WC_EDIT, "LAYER EDIT COLORS" },
    { 5, W_NONE, "LAYER CALC VALUES" },
    { 6, W_NONE, "LAYER LUT VALUE LABEL" },
    { 7, W_NONE, "LAYER DISPLAY LAYER GB" },
    { 8, W_NONE, "LAYER DISPLAY ALL" },
    { 9, W_NONE, "LAYER DISPLAY DISPLAY GB" },
    { 10, W_NONE, "LAYER DISPLAY LUT GB" },
    { 11, W_NONE, "LAYER LUT START LABEL" },
    { 12, W_NONE, "LAYER LUT END LABEL" },
    { 13, W_NONE, "LAYER LUT START" },
    { 14, W_NONE, "LAYER LUT END" },
    { 15, W_NONE, "LAYER DISPLAY OK" },
    { 16, W_NONE, "LAYER DISPLAY HELP" },
    { 17, W_NONE, "LAYER DISPLAY CANCEL" },
    { 18, W_NONE, "LAYER LUT VALUE" },
    { 19, W_NONE, "LAYER LUT STRETCH" },
    { 20, W_NONE, "LAYER SHOW TOPO" },
};

static const DialogCtlEntry g_ctls_178[] = {
    { 1, W_NONE, "WINPOS LIST GB" },
    { 2, W_NONE, "WINPOS WINDOW LIST" },
    { 3, W_NONE, "WINPOS X BAR" },
    { 4, W_NONE, "WINPOS Y BAR" },
    { 5, W_NONE, "WINPOS WIDTH BAR" },
    { 6, W_NONE, "WINPOS HEIGHT BAR" },
    { 7, W_NONE, "WINPOS X" },
    { 8, W_NONE, "WINPOS Y" },
    { 9, W_NONE, "WINPOS WIDTH" },
    { 10, W_NONE, "WINPOS HEIGHT" },
    { 11, W_NONE, "WINPOS X LABEL" },
    { 12, W_NONE, "WINPOS Y LABEL" },
    { 13, W_NONE, "WINPOS WIDTH LABEL" },
    { 14, W_NONE, "WINPOS HEIGHT LABEL" },
    { 15, W_NONE, "WINPOS POSITION GB" },
    { 16, W_NONE, "WINPOS OK" },
    { 17, W_NONE, "WINPOS CANCEL" },
    { 18, W_NONE, "WINPOS HELP" },
};

static const DialogCtlEntry g_ctls_179[] = {
    { 1, W_NONE, "ASCII ROWS LABEL" },
    { 2, W_NONE, "ASCII COLS LABEL" },
    { 3, W_NONE, "ASCII CELL SIZE LABEL" },
    { 4, W_NONE, "ASCII ROWS" },
    { 5, W_NONE, "ASCII COLS" },
    { 6, W_NONE, "ASCII CELL SIZE" },
    { 7, W_NONE, "ASCII GB" },
    { 8, W_NONE, "ASCII IMAGE OPTION CANCEL" },
    { 9, W_NONE, "ASCII IMAGE OPTION OK" },
    { 10, W_NONE, "ASCII IMAGE OPTION HELP" },
    { 11, W_NONE, "ASCII IMAGE REGISTRATION GB" },
    { 12, W_NONE, "ASCII IMAGE EASTING" },
    { 13, W_NONE, "ASCII IMAGE NORTHING" },
    { 14, W_NONE, "ASCII IMAGE EASTING LABEL" },
    { 15, W_NONE, "ASCII IMAGE NORTHING LABEL" },
    { 16, W_NONE, "ASCII IMAGE REG LABEL" },
    { 17, W_NONE, "ASCII IMAGE FIELD GB" },
    { 18, W_NONE, "ASCII IMAGE INCLINATION" },
    { 19, W_NONE, "ASCII IMAGE DECLINATION" },
    { 20, W_NONE, "ASCII IMAGE INTENSITY" },
    { 21, W_NONE, "ASCII IMAGE ALTITUDE" },
    { 22, WC_TEXT, "REFERENCE IMAGE OPTIONS TEXT 55" },
    { 23, W_NONE, "ASCII IMAGE DECL LABEL" },
    { 24, W_NONE, "ASCII IMAGE INTENSITY LABEL" },
    { 25, W_NONE, "ASCII IMAGE ALTITUDE LABEL" },
    { 26, W_NONE, "ASCII IMAGE TYPE GB" },
    { 27, W_NONE, "ASCII IMAGE GRAVITY" },
    { 28, W_NONE, "ASCII IMAGE MAGNETICS" },
    { 29, W_NONE, "ASCII IMAGE FLIP XY" },
};

static const DialogCtlEntry g_ctls_180[] = {
    { 1, W_NONE, "DXF IMPORT X LABEL" },
    { 2, W_NONE, "DXF IMPORT Y LABEL" },
    { 3, W_NONE, "DXF IMPORT Z LABEL" },
    { 4, W_NONE, "DXF IMPORT MIN X" },
    { 5, W_NONE, "DXF IMPORT MIN Y" },
    { 6, W_NONE, "DXF IMPORT MIN Z" },
    { 7, W_NONE, "DXF IMPORT MAX X" },
    { 8, W_NONE, "DXF IMPORT MAX Y" },
    { 9, W_NONE, "DXF IMPORT MAX Z" },
    { 10, W_NONE, "DXF IMPORT DIM GB" },
    { 11, W_NONE, "DXF IMPORT TO X" },
    { 12, W_NONE, "DXF IMPORT TO Y" },
    { 13, W_NONE, "DXF IMPORT TO Z" },
    { 14, W_NONE, "DXF IMPORT BLOCK LABEL" },
    { 15, W_NONE, "DXF IMPORT BLOCK" },
    { 16, W_NONE, "DXF IMPORT NUM CUBES" },
    { 17, WC_PUSHBUTTON, "DXF IMPORT WINDOW PUSHBUTTON 127" },
    { 18, WC_PUSHBUTTON, "DXF IMPORT WINDOW PUSHBUTTON 129" },
    { 19, WC_PUSHBUTTON, "DXF IMPORT WINDOW PUSHBUTTON 130" },
};

static const DialogCtlEntry g_ctls_181[] = {
    { 1, W_NONE, "ASSIGN PROP LIST" },
    { 2, WC_EDIT, "ASSIGN PROP EDIT" },
    { 3, W_NONE, "ASSIGN PROP OK" },
    { 4, W_NONE, "ASSIGN PROP CANCEL" },
    { 5, W_NONE, "ASSIGN PROP HELP" },
};

static const DialogCtlEntry g_ctls_182[] = {
    { 1, W_NONE, "FILE ORDER GB" },
    { 2, W_NONE, "FILE ORDER X LABEL" },
    { 3, W_NONE, "FILE ORDER Y LABEL" },
    { 4, W_NONE, "FILE ORDER Z LABEL" },
    { 5, W_NONE, "FILE ORDER X1" },
    { 6, W_NONE, "FILE ORDER X2" },
    { 7, W_NONE, "FILE ORDER X3" },
    { 8, W_NONE, "FILE ORDER Y1" },
    { 9, W_NONE, "FILE ORDER Y2" },
    { 10, W_NONE, "FILE ORDER Y3" },
    { 11, W_NONE, "FILE ORDER Z1" },
    { 12, W_NONE, "FILE ORDER Z2" },
    { 13, W_NONE, "FILE ORDER Z3" },
    { 14, W_NONE, "FILE DIRECTION GB" },
    { 15, W_NONE, "FILE DIR X LABEL" },
    { 16, W_NONE, "FILE DIR Y LABEL" },
    { 17, W_NONE, "FILE DIR Z LABEL" },
    { 18, W_NONE, "FILE DIR X EW" },
    { 19, W_NONE, "FILE DIR X WE" },
    { 20, W_NONE, "FILE DIR Y NS" },
    { 21, W_NONE, "FILE DIR Y SN" },
    { 22, W_NONE, "FILE DIR Z UD" },
    { 23, W_NONE, "FILE DIR Z DU" },
    { 24, W_NONE, "FILE FORMAT OK" },
    { 25, W_NONE, "FILE FORMAT CANCEL" },
    { 26, W_NONE, "FILE FORMAT HELP" },
    { 27, W_NONE, "FILE PROPERTY" },
    { 28, W_NONE, "FILE PROPERTIES GB" },
    { 29, W_NONE, "FILE SINGLE VALUE" },
};

static const DialogCtlEntry g_ctls_183[] = {
    { 1, W_NONE, "OPTIONS PREVIEW" },
    { 2, W_NONE, "OPTIONS SELECTION" },
    { 3, W_NONE, "OPTIONS SELECTION GB" },
    { 4, WC_PUSHBUTTON, "OPTIONS WINDOW PUSHBUTTON 107" },
    { 5, WC_PUSHBUTTON, "OPTIONS WINDOW PUSHBUTTON 108" },
    { 6, WC_PUSHBUTTON, "OPTIONS WINDOW PUSHBUTTON 109" },
};

static const DialogCtlEntry g_ctls_184[] = {
    { 1, WC_GROUPBOX, "CHAIR WINDOW GROUPBOX 51" },
    { 2, W_NONE, "CHAIR X BAR" },
    { 3, W_NONE, "CHAIR Y BAR" },
    { 4, W_NONE, "CHAIR Z BAR" },
    { 5, W_NONE, "CHAIR X LABEL" },
    { 6, W_NONE, "CHAIR Y LABEL" },
    { 7, W_NONE, "CHAIR Z LABEL" },
    { 8, W_NONE, "CHAIR X" },
    { 9, W_NONE, "CHAIR Z" },
    { 10, W_NONE, "CHAIR Y" },
    { 11, W_NONE, "CHAIR USE" },
};

static const DialogCtlEntry g_ctls_185[] = {
    { 1, W_NONE, "THREED DECL LABEL" },
    { 2, W_NONE, "THREED AZIMUTH LABEL" },
    { 3, W_NONE, "THREED SCALE LABEL" },
    { 4, W_NONE, "THREED DECL BAR" },
    { 5, W_NONE, "THREED AZIMUTH BAR" },
    { 6, W_NONE, "THREED SCALE BAR" },
    { 7, W_NONE, "THREED DECL" },
    { 8, W_NONE, "THREED AZIMUTH" },
    { 9, W_NONE, "THREED SCALE" },
    { 10, W_NONE, "THREED VIEW GB" },
    { 11, W_NONE, "THREED SCALE PERCENT LABEL" },
};

static const DialogCtlEntry g_ctls_186[] = {
    { 1, W_NONE, "NEWWIN EACHTIME" },
};

static const DialogCtlEntry g_ctls_187[] = {
    { 1, W_NONE, "GENERATE GB" },
    { 2, W_NONE, "GENERATE GRAVITY" },
    { 3, W_NONE, "GENERATE MAGNETICS" },
    { 4, W_NONE, "GENERATE COMPONENTS" },
};

static const DialogCtlEntry g_ctls_188[] = {
    { 1, W_NONE, "FIELD INCLINATION LABEL" },
    { 2, W_NONE, "FIELD INTENSITY LABEL" },
    { 3, W_NONE, "FIELD INTENSITY" },
    { 4, W_NONE, "FIELD INCLINATION" },
    { 5, W_NONE, "FIELD DECLINATION LABEL" },
    { 6, W_NONE, "FIELD DECLINATION" },
    { 7, WC_GROUPBOX, "FIELD WINDOW GROUPBOX 158" },
    { 8, W_NONE, "FIELD FIXED" },
    { 9, W_NONE, "FIELD VARIABLE" },
    { 10, W_NONE, "FIELD X POS LABEL" },
    { 11, W_NONE, "FIELD Y POS LABEL" },
    { 12, W_NONE, "FIELD Z POS LABEL" },
    { 13, W_NONE, "FIELD X POS" },
    { 14, W_NONE, "FIELD Y POS" },
    { 15, W_NONE, "FIELD Z POS" },
    { 16, W_NONE, "FIELD XYZ" },
    { 17, W_NONE, "FIELD DECL" },
    { 18, W_NONE, "FIELD INCL" },
    { 19, W_NONE, "FIELD INTEN" },
};

static const DialogCtlEntry g_ctls_189[] = {
    { 1, W_NONE, "ALTITUDE SURFACE" },
    { 2, W_NONE, "ALTITUDE AIRBORNE" },
    { 3, W_NONE, "ALTITUDE GB" },
    { 4, W_NONE, "ALTITUDE UNIT LABEL" },
    { 5, W_NONE, "ALTITUDE HEIGHT" },
};

static const DialogCtlEntry g_ctls_190[] = {
    { 1, W_NONE, "DRAPED SURVEY" },
};

static const DialogCtlEntry g_ctls_191[] = {
    { 1, W_NONE, "RANGE CONV LABEL" },
    { 2, W_NONE, "RANGE CONV" },
    { 3, W_NONE, "RANGE CONV UNIT LABEL" },
    { 4, W_NONE, "RANGE CONV IN CUBES LABEL" },
    { 5, W_NONE, "RANGE GB" },
    { 6, W_NONE, "RANGE ANALYTIC LABEL" },
    { 7, W_NONE, "RANGE ANALYTIC" },
    { 8, W_NONE, "RANGE ANALYTIC IN CUBES LABEL" },
    { 9, W_NONE, "RANGE ANALYTIC UNIT LABEL" },
    { 10, W_NONE, "RANGE ALL EXACT" },
    { 11, W_NONE, "RANGE REAL GEOLOGY PADDING" },
};

static const DialogCtlEntry g_ctls_192[] = {
    { 1, W_NONE, "CALC TYPE GB" },
    { 2, W_NONE, "CALC TYPE LIST" },
    { 3, W_NONE, "CALC TYPE PROJECT FIELDS" },
};

static const DialogCtlEntry g_ctls_193[] = {
    { 1, W_NONE, "DEFORM FIELD REMANENCE" },
    { 2, W_NONE, "DEFORM FIELD ANISOTROPY" },
    { 3, W_NONE, "DEFORM FIELD GB" },
};

static const DialogCtlEntry g_ctls_194[] = {
    { 1, W_NONE, "PADDING GB" },
    { 2, W_NONE, "PADDING TYPE" },
    { 3, W_NONE, "PADDING SUSX LABEL" },
    { 4, W_NONE, "PADDING SUSX" },
    { 5, W_NONE, "PADDING TYPE LABEL" },
    { 6, W_NONE, "PADDING SUSY LABEL" },
    { 7, W_NONE, "PADDING SUSY" },
    { 8, W_NONE, "PADDING SUSZ LABEL" },
    { 9, W_NONE, "PADDING SUSZ" },
    { 10, W_NONE, "PADDING DENSITY LABEL" },
    { 11, W_NONE, "PADDING DENSITY" },
    { 12, W_NONE, "PADDING FENCE LABEL" },
    { 13, W_NONE, "PADDING FENCE" },
    { 14, W_NONE, "PADDING PERCENT LABEL" },
    { 15, W_NONE, "PADDING PERCENT" },
};

static const DialogCtlEntry g_ctls_195[] = {
    { 1, W_NONE, "VARIABLE CUBE RATIO" },
    { 2, W_NONE, "VARIABLE CUBE RATIO LABEL" },
    { 3, W_NONE, "VARIABLE CUBE CUTOFF" },
    { 4, W_NONE, "VARIABLE CUBE GB" },
    { 5, W_NONE, "VARIABLE CUBE CUTOFF LABEL" },
};

static const DialogCtlEntry g_ctls_196[] = {
    { 1, W_NONE, "SUS UNITS SI" },
    { 2, W_NONE, "SUS UNITS CGS" },
    { 3, W_NONE, "SUS UNITS GB" },
};

static const DialogCtlEntry g_ctls_197[] = {
    { 1, W_NONE, "GEOPHYSICS SCALE LABEL1" },
    { 2, W_NONE, "GEOPHYSICS SCALE LABEL2" },
    { 3, W_NONE, "GEOPHYSICS SCALE" },
    { 4, W_NONE, "GEOPHYSICS SCALE GB" },
};

static const DialogCtlEntry g_ctls_198[] = {
    { 1, W_NONE, "GEOPHYSICS GRAVITY IDISPLAY" },
    { 2, W_NONE, "GEOPHYSICS MAGNETICS IDISPLAY" },
};

static const DialogCtlEntry g_ctls_199[] = {
    { 1, W_NONE, "LOCAL REMOTE GB" },
    { 2, W_NONE, "LOCAL REMOTE REMOTE" },
    { 3, W_NONE, "LOCAL REMOTE LOCAL" },
};

static const DialogCtlEntry g_ctls_200[] = {
    { 1, W_NONE, "UNIT METERS" },
    { 2, W_NONE, "UNIT FEET" },
    { 3, W_NONE, "UNIT WINDOW GB" },
};

static const DialogCtlEntry g_ctls_201[] = {
    { 1, W_NONE, "PRINT SCALE LABEL1" },
    { 2, W_NONE, "PRINT SCALE LABEL2" },
    { 3, W_NONE, "PRINT SCALE" },
    { 4, W_NONE, "PRINT SCALE GB" },
};

static const DialogCtlEntry g_ctls_202[] = {
    { 1, W_NONE, "WINPOSITION LIST GB" },
    { 2, W_NONE, "WINPOSITION LIST" },
    { 3, W_NONE, "WINPOSITION X BAR" },
    { 4, W_NONE, "WINPOSITION Y BAR" },
    { 5, W_NONE, "WINPOSITION WIDTH BAR" },
    { 6, W_NONE, "WINPOSITION HEIGHT BAR" },
    { 7, W_NONE, "WINPOSITION X" },
    { 8, W_NONE, "WINPOSITION Y" },
    { 9, W_NONE, "WINPOSITION WIDTH" },
    { 10, W_NONE, "WINPOSITION HEIGHT" },
    { 11, W_NONE, "WINPOSITION X LABEL" },
    { 12, W_NONE, "WINPOSITION Y LABEL" },
    { 13, W_NONE, "WINPOSITION WIDTH LABEL" },
    { 14, W_NONE, "WINPOSITION HEIGHT LABEL" },
    { 15, W_NONE, "WINPOSITION POS GB" },
};

static const DialogCtlEntry g_ctls_203[] = {
    { 1, W_NONE, "VIEW NAME NAME" },
    { 2, W_NONE, "VIEW NAME DELETE" },
    { 3, W_NONE, "VIEW NAME GB" },
    { 4, W_NONE, "VIEW NAME LIST" },
};

static const DialogCtlEntry g_ctls_204[] = {
    { 1, W_NONE, "CUBE SIZE GB" },
    { 2, W_NONE, "CUBE SIZE GEOLOGY" },
    { 3, W_NONE, "CUBE SIZE GEOPHYSICS" },
    { 4, W_NONE, "CUBE SIZE GEOLOGY LABEL" },
    { 5, W_NONE, "CUBE SIZE GEOPHYSICS LABEL" },
};

static const DialogCtlEntry g_ctls_205[] = {
    { 1, W_NONE, "ORIGIN GB" },
    { 2, W_NONE, "ORIGIN X BAR" },
    { 3, W_NONE, "ORIGIN Y BAR" },
    { 4, W_NONE, "ORIGIN Z BAR" },
    { 5, W_NONE, "ORIGIN X LABEL" },
    { 6, W_NONE, "ORIGIN Y LABEL" },
    { 7, W_NONE, "ORIGIN Z LABEL" },
    { 8, W_NONE, "ORIGIN X" },
    { 9, W_NONE, "ORIGIN Z" },
    { 10, W_NONE, "ORIGIN Y" },
};

static const DialogCtlEntry g_ctls_206[] = {
    { 1, W_NONE, "DIMENSION GB" },
    { 2, W_NONE, "DIMENSION X BAR" },
    { 3, W_NONE, "DIMENSION Y BAR" },
    { 4, W_NONE, "DIMENSION Z BAR" },
    { 5, W_NONE, "DIMENSION X LABEL" },
    { 6, W_NONE, "DIMENSION Y LABEL" },
    { 7, W_NONE, "DIMENSION Z LABEL" },
    { 8, W_NONE, "DIMENSION X" },
    { 9, W_NONE, "DIMENSION Z" },
    { 10, W_NONE, "DIMENSION Y" },
};

static const DialogCtlEntry g_ctls_207[] = {
    { 1, W_NONE, "USE TOPOGRAPHY" },
};

static const DialogCtlEntry g_ctls_208[] = {
    { 1, W_NONE, "FALSE ORIGIN GB" },
    { 2, W_NONE, "FALSE ORIGIN EASTING" },
    { 3, W_NONE, "FALSE ORIGIN NORTHING" },
    { 4, W_NONE, "FALSE ORIGIN EASTING LABEL" },
    { 5, W_NONE, "FALSE ORIGIN NORTHING LABEL" },
};

static const DialogCtlEntry g_ctls_209[] = {
    { 1, W_NONE, "MOVIE GENERATION FRAMES LABEL" },
    { 2, W_NONE, "MOVIE GENERATION FRAMES" },
    { 3, W_NONE, "MOVIE REPLAY SPEED LABEL" },
    { 4, W_NONE, "MOVIE REPLAY SPEED BAR" },
    { 5, W_NONE, "MOVIE REPLAY FAST LABEL" },
    { 6, W_NONE, "MOVIE REPLAY SLOW LABEL" },
    { 7, W_NONE, "MOVIE REPLAY SPEED" },
    { 8, W_NONE, "MOVIE GENERATION GB" },
    { 9, W_NONE, "MOVIE GENERATION TYPE" },
    { 10, W_NONE, "MOVIE GENERATION TYPE LABEL" },
    { 11, W_NONE, "MOVIE REPLAY GB" },
};

static const DialogCtlEntry g_ctls_210[] = {
    { 1, W_NONE, "BOREHOLE GB" },
    { 2, W_NONE, "BOREHOLE DECL LABEL" },
    { 3, W_NONE, "BOREHOLE LENGTH LABEL" },
    { 4, W_NONE, "BOREHOLE DECL BAR" },
    { 5, W_NONE, "BOREHOLE LENGTH BAR" },
    { 6, W_NONE, "BOREHOLE DIP" },
    { 7, W_NONE, "BOREHOLE LENGTH" },
    { 8, W_NONE, "BOREHOLE DECL" },
    { 9, W_NONE, "BOREHOLE DIP LABEL" },
    { 10, W_NONE, "BOREHOLE DIP BAR" },
    { 11, W_NONE, "BOREHOLE POS X BAR" },
    { 12, W_NONE, "BOREHOLE POS Y BAR" },
    { 13, W_NONE, "BOREHOLE POS Z BAR" },
    { 14, W_NONE, "BOREHOLE POS X LABEL" },
    { 15, W_NONE, "BOREHOLE POS Y LABEL" },
    { 16, W_NONE, "BOREHOLE POS Z LABEL" },
    { 17, W_NONE, "BOREHOLE POS X" },
    { 18, W_NONE, "BOREHOLE POS Z" },
    { 19, W_NONE, "BOREHOLE POS Y" },
};

static const DialogCtlEntry g_ctls_211[] = {
    { 1, W_NONE, "SECTION GB" },
    { 2, W_NONE, "SECTION DECL LABEL" },
    { 3, W_NONE, "SECTION LENGTH LABEL" },
    { 4, W_NONE, "SECTION DECL BAR" },
    { 5, W_NONE, "SECTION LENGTH BAR" },
    { 6, W_NONE, "SECTION LENGTH" },
    { 7, W_NONE, "SECTION DECL" },
    { 8, W_NONE, "SECTION POS X BAR" },
    { 9, W_NONE, "SECTION POS Y BAR" },
    { 10, W_NONE, "SECTION POS Z BAR" },
    { 11, W_NONE, "SECTION POS X LABEL" },
    { 12, W_NONE, "SECTION POS Y LABEL" },
    { 13, W_NONE, "SECTION POS Z LABEL" },
    { 14, W_NONE, "SECTION POS X" },
    { 15, W_NONE, "SECTION POS Z" },
    { 16, W_NONE, "SECTION POS Y" },
    { 17, W_NONE, "SECTION HEIGHT LABEL" },
    { 18, W_NONE, "SECTION HEIGHT BAR" },
    { 19, W_NONE, "SECTION HEIGHT" },
};

static const DialogCtlEntry g_ctls_214[] = {
    { 1, W_NONE, "BACKGROUND BUTTON" },
};

static const DialogCtlEntry g_ctls_215[] = {
    { 1, W_NONE, "SURFACE SELECTION LIST" },
    { 2, W_NONE, "SURFACE SELECTION ALL" },
    { 3, W_NONE, "SURFACE SELECTION TYPE" },
    { 4, W_NONE, "SURFACE SELECTION TYPE LABEL" },
    { 5, W_NONE, "SURFACE SELECTION GB" },
};

static const DialogCtlEntry g_ctls_216[] = {
    { 1, WC_EDIT, "VOLUME EDIT" },
    { 2, W_NONE, "VOLUME GB" },
};

static const DialogCtlEntry g_ctls_217[] = {
    { 1, WC_GROUPBOX, "HELP OPTION GROUPBOX" },
    { 2, W_NONE, "HELP VIEWER LABEL" },
    { 3, W_NONE, "HELP VIEWER" },
    { 4, W_NONE, "HELP VIEWER INFO" },
    { 1, W_NONE, "STRING 1" },
    { 3, W_NONE, "CHOICE FIRST" },
    { 5, W_NONE, "CHOICE LAST" },
};

/* [Qt port ADDITION] todo.txt #44 -- new "Gaussian Noise" sub-panel on
 * the Geophysics Calculation options tab (see optnlib.c/noisewin.c). */
static const DialogCtlEntry g_ctls_218[] = {
    { 1, WC_GROUPBOX, "NOISE GB" },
    { 2, WC_CHECKBOX, "Add Gaussian Noise" },
    { 3, WC_TEXT, "Sigma (%):" },
    { 4, WC_EDIT, "NOISE SIGMA" },
    { 5, WC_TEXT, "Seed (0=rand):" },
    { 6, WC_EDIT, "NOISE SEED" },
};

extern const DialogEntry g_dialogRegistry[] = {
    { 104, "DEFINE COLOUR WINDOW", g_ctls_104, (int)(sizeof(g_ctls_104)/sizeof(g_ctls_104[0])) },
    { 105, "PROFILE WINDOW", g_ctls_105, (int)(sizeof(g_ctls_105)/sizeof(g_ctls_105[0])) },
    { 116, "GEOLOGY OPTIONS WINDOW", g_ctls_116, (int)(sizeof(g_ctls_116)/sizeof(g_ctls_116[0])) },
    { 117, "VIEW OPTIONS WINDOW", g_ctls_117, (int)(sizeof(g_ctls_117)/sizeof(g_ctls_117[0])) },
    { 121, "PROJECT OPTIONS WINDOW", g_ctls_121, (int)(sizeof(g_ctls_121)/sizeof(g_ctls_121[0])) },
    { 123, "GEOPHYSICS OPTIONS WINDOW", g_ctls_123, (int)(sizeof(g_ctls_123)/sizeof(g_ctls_123[0])) },
    { 124, "JOB STATUS WINDOW", g_ctls_124, (int)(sizeof(g_ctls_124)/sizeof(g_ctls_124[0])) },
    { 125, "TOPO OPTIONS WINDOW", g_ctls_125, (int)(sizeof(g_ctls_125)/sizeof(g_ctls_125[0])) },
    { 126, "DLG 126", g_ctls_126, (int)(sizeof(g_ctls_126)/sizeof(g_ctls_126[0])) },
    { 127, "PARALLEL OPTIONS WINDOW", g_ctls_127, (int)(sizeof(g_ctls_127)/sizeof(g_ctls_127[0])) },
    { 128, "MOVIE OPTIONS", g_ctls_128, (int)(sizeof(g_ctls_128)/sizeof(g_ctls_128[0])) },
    { 132, "BLOCK CONVERT WINDOW", g_ctls_132, (int)(sizeof(g_ctls_132)/sizeof(g_ctls_132[0])) },
    { 133, "XYZ GENERATION WINDOW", g_ctls_133, (int)(sizeof(g_ctls_133)/sizeof(g_ctls_133[0])) },
    { 134, "XYZ CONVERT WINDOW", g_ctls_134, (int)(sizeof(g_ctls_134)/sizeof(g_ctls_134[0])) },
    { 135, "ROCK DATABASE WIN", g_ctls_135, (int)(sizeof(g_ctls_135)/sizeof(g_ctls_135[0])) },
    { 136, "PROFILE OPTION WINDOW", g_ctls_136, (int)(sizeof(g_ctls_136)/sizeof(g_ctls_136[0])) },
    { 137, "EVENT WINDOW", g_ctls_137, (int)(sizeof(g_ctls_137)/sizeof(g_ctls_137[0])) },
    { 138, "PREVIEW WINDOW", g_ctls_138, (int)(sizeof(g_ctls_138)/sizeof(g_ctls_138[0])) },
    { 139, "XYZ WINDOW", g_ctls_139, (int)(sizeof(g_ctls_139)/sizeof(g_ctls_139[0])) },
    { 140, "DDP WINDOW", g_ctls_140, (int)(sizeof(g_ctls_140)/sizeof(g_ctls_140[0])) },
    { 141, "ROTATION WINDOW", g_ctls_141, (int)(sizeof(g_ctls_141)/sizeof(g_ctls_141[0])) },
    { 142, "PP WINDOW", g_ctls_142, (int)(sizeof(g_ctls_142)/sizeof(g_ctls_142[0])) },
    { 143, "GMA WINDOW", g_ctls_143, (int)(sizeof(g_ctls_143)/sizeof(g_ctls_143[0])) },
    { 144, "ALT WINDOW", g_ctls_144, (int)(sizeof(g_ctls_144)/sizeof(g_ctls_144[0])) },
    { 145, "DDD WINDOW", g_ctls_145, (int)(sizeof(g_ctls_145)/sizeof(g_ctls_145[0])) },
    { 146, "MATRIX WINDOW", g_ctls_146, (int)(sizeof(g_ctls_146)/sizeof(g_ctls_146[0])) },
    { 148, "ROCK WINDOW", g_ctls_148, (int)(sizeof(g_ctls_148)/sizeof(g_ctls_148[0])) },
    { 152, "FFOLD WINDOW", g_ctls_152, (int)(sizeof(g_ctls_152)/sizeof(g_ctls_152[0])) },
    { 153, "FDSCL WINDOW", g_ctls_153, (int)(sizeof(g_ctls_153)/sizeof(g_ctls_153[0])) },
    { 154, "TGMA WINDOW", g_ctls_154, (int)(sizeof(g_ctls_154)/sizeof(g_ctls_154[0])) },
    { 155, "FSCL WINDOW", g_ctls_155, (int)(sizeof(g_ctls_155)/sizeof(g_ctls_155[0])) },
    { 156, "SSCL WINDOW", g_ctls_156, (int)(sizeof(g_ctls_156)/sizeof(g_ctls_156[0])) },
    { 157, "FDYKE WINDOW", g_ctls_157, (int)(sizeof(g_ctls_157)/sizeof(g_ctls_157[0])) },
    { 158, "SW WINDOW", g_ctls_158, (int)(sizeof(g_ctls_158)/sizeof(g_ctls_158[0])) },
    { 159, "FPLUG WINDOW", g_ctls_159, (int)(sizeof(g_ctls_159)/sizeof(g_ctls_159[0])) },
    { 160, "PSCL WINDOW", g_ctls_160, (int)(sizeof(g_ctls_160)/sizeof(g_ctls_160[0])) },
    { 161, "AXIS WINDOW", g_ctls_161, (int)(sizeof(g_ctls_161)/sizeof(g_ctls_161[0])) },
    { 162, "CORNER WINDOW", g_ctls_162, (int)(sizeof(g_ctls_162)/sizeof(g_ctls_162[0])) },
    { 163, "IPROP WINDOW", g_ctls_163, (int)(sizeof(g_ctls_163)/sizeof(g_ctls_163[0])) },
    { 164, "ISCL WINDOW", g_ctls_164, (int)(sizeof(g_ctls_164)/sizeof(g_ctls_164[0])) },
    { 165, "SURFACE WINDOW", g_ctls_165, (int)(sizeof(g_ctls_165)/sizeof(g_ctls_165[0])) },
    { 166, "FOLD TRACE WINDOW", g_ctls_166, (int)(sizeof(g_ctls_166)/sizeof(g_ctls_166[0])) },
    { 167, "FAULT TRACE WINDOW", g_ctls_167, (int)(sizeof(g_ctls_167)/sizeof(g_ctls_167[0])) },
    { 168, "TRACE BUTTON WINDOW", g_ctls_168, (int)(sizeof(g_ctls_168)/sizeof(g_ctls_168[0])) },
    { 169, "STRATIGRAPHY WINDOW", g_ctls_169, (int)(sizeof(g_ctls_169)/sizeof(g_ctls_169[0])) },
    { 170, "GENERIC WINDOW", g_ctls_170, (int)(sizeof(g_ctls_170)/sizeof(g_ctls_170[0])) },
    { 171, "TIME WINDOW", g_ctls_171, (int)(sizeof(g_ctls_171)/sizeof(g_ctls_171[0])) },
    { 172, "PREVIEW MENU WINDOW", g_ctls_172, (int)(sizeof(g_ctls_172)/sizeof(g_ctls_172[0])) },
    { 173, "LICENCE WINDOW", g_ctls_173, (int)(sizeof(g_ctls_173)/sizeof(g_ctls_173[0])) },
    { 174, "IMAGE OPTION WINDOW", g_ctls_174, (int)(sizeof(g_ctls_174)/sizeof(g_ctls_174[0])) },
    { 175, "CONTACT WINDOW", g_ctls_175, (int)(sizeof(g_ctls_175)/sizeof(g_ctls_175[0])) },
    { 176, "VIEW WINDOW", g_ctls_176, (int)(sizeof(g_ctls_176)/sizeof(g_ctls_176[0])) },
    { 177, "LAYER DISPLAY WINDOW", g_ctls_177, (int)(sizeof(g_ctls_177)/sizeof(g_ctls_177[0])) },
    { 178, "WINPOS WINDOW", g_ctls_178, (int)(sizeof(g_ctls_178)/sizeof(g_ctls_178[0])) },
    { 179, "ASCII IMAGE OPTIONS", g_ctls_179, (int)(sizeof(g_ctls_179)/sizeof(g_ctls_179[0])) },
    { 180, "DXF IMPORT WINDOW", g_ctls_180, (int)(sizeof(g_ctls_180)/sizeof(g_ctls_180[0])) },
    { 181, "ASSIGN PROP WINDOW", g_ctls_181, (int)(sizeof(g_ctls_181)/sizeof(g_ctls_181[0])) },
    { 182, "FILE FORMAT WINDOW", g_ctls_182, (int)(sizeof(g_ctls_182)/sizeof(g_ctls_182[0])) },
    { 183, "OPTIONS WINDOW", g_ctls_183, (int)(sizeof(g_ctls_183)/sizeof(g_ctls_183[0])) },
    { 184, "CHAIR WINDOW", g_ctls_184, (int)(sizeof(g_ctls_184)/sizeof(g_ctls_184[0])) },
    { 185, "THREED VIEW WINDOW", g_ctls_185, (int)(sizeof(g_ctls_185)/sizeof(g_ctls_185[0])) },
    { 186, "NEWWIN WINDOW", g_ctls_186, (int)(sizeof(g_ctls_186)/sizeof(g_ctls_186[0])) },
    { 187, "GENERATE WINDOW", g_ctls_187, (int)(sizeof(g_ctls_187)/sizeof(g_ctls_187[0])) },
    { 188, "FIELD WINDOW", g_ctls_188, (int)(sizeof(g_ctls_188)/sizeof(g_ctls_188[0])) },
    { 189, "ALTITUDE WINDOW", g_ctls_189, (int)(sizeof(g_ctls_189)/sizeof(g_ctls_189[0])) },
    { 190, "DRAPED SURVEY WINDOW", g_ctls_190, (int)(sizeof(g_ctls_190)/sizeof(g_ctls_190[0])) },
    { 191, "RANGE WINDOW", g_ctls_191, (int)(sizeof(g_ctls_191)/sizeof(g_ctls_191[0])) },
    { 192, "CALC TYPE WINDOW", g_ctls_192, (int)(sizeof(g_ctls_192)/sizeof(g_ctls_192[0])) },
    { 193, "DEFORM FIELD WINDOW", g_ctls_193, (int)(sizeof(g_ctls_193)/sizeof(g_ctls_193[0])) },
    { 194, "PADDING WINDOW", g_ctls_194, (int)(sizeof(g_ctls_194)/sizeof(g_ctls_194[0])) },
    { 195, "VARIABLE CUBE WINDOW", g_ctls_195, (int)(sizeof(g_ctls_195)/sizeof(g_ctls_195[0])) },
    { 196, "SUS UNITS WINDOW", g_ctls_196, (int)(sizeof(g_ctls_196)/sizeof(g_ctls_196[0])) },
    { 197, "GEOPHYSICS SCALE WINDOW", g_ctls_197, (int)(sizeof(g_ctls_197)/sizeof(g_ctls_197[0])) },
    { 198, "GEOPHYSICS IDISPLAY WINDOW", g_ctls_198, (int)(sizeof(g_ctls_198)/sizeof(g_ctls_198[0])) },
    { 199, "LOCAL REMOTE WINDOW", g_ctls_199, (int)(sizeof(g_ctls_199)/sizeof(g_ctls_199[0])) },
    { 200, "UNIT WINDOW", g_ctls_200, (int)(sizeof(g_ctls_200)/sizeof(g_ctls_200[0])) },
    { 201, "PRINT SCALE WINDOW", g_ctls_201, (int)(sizeof(g_ctls_201)/sizeof(g_ctls_201[0])) },
    { 202, "WINPOSITION WINDOW", g_ctls_202, (int)(sizeof(g_ctls_202)/sizeof(g_ctls_202[0])) },
    { 203, "VIEW NAME WINDOW", g_ctls_203, (int)(sizeof(g_ctls_203)/sizeof(g_ctls_203[0])) },
    { 204, "CUBE SIZE WINDOW", g_ctls_204, (int)(sizeof(g_ctls_204)/sizeof(g_ctls_204[0])) },
    { 205, "ORIGIN WINDOW", g_ctls_205, (int)(sizeof(g_ctls_205)/sizeof(g_ctls_205[0])) },
    { 206, "DIMENSION WINDOW", g_ctls_206, (int)(sizeof(g_ctls_206)/sizeof(g_ctls_206[0])) },
    { 207, "USE TOPOGRAPHY WINDOW", g_ctls_207, (int)(sizeof(g_ctls_207)/sizeof(g_ctls_207[0])) },
    { 208, "FALSE ORIGIN WINDOW", g_ctls_208, (int)(sizeof(g_ctls_208)/sizeof(g_ctls_208[0])) },
    { 209, "MOVIE WINDOW", g_ctls_209, (int)(sizeof(g_ctls_209)/sizeof(g_ctls_209[0])) },
    { 210, "BOREHOLE WINDOW", g_ctls_210, (int)(sizeof(g_ctls_210)/sizeof(g_ctls_210[0])) },
    { 211, "SECTION WINDOW", g_ctls_211, (int)(sizeof(g_ctls_211)/sizeof(g_ctls_211[0])) },
    { 214, "BACKGROUND WINDOW", g_ctls_214, (int)(sizeof(g_ctls_214)/sizeof(g_ctls_214[0])) },
    { 215, "SURFACE SELECTION WINDOW", g_ctls_215, (int)(sizeof(g_ctls_215)/sizeof(g_ctls_215[0])) },
    { 216, "VOLUME WINDOW", g_ctls_216, (int)(sizeof(g_ctls_216)/sizeof(g_ctls_216[0])) },
    { 217, "HELP OPTION WINDOW", g_ctls_217, (int)(sizeof(g_ctls_217)/sizeof(g_ctls_217[0])) },
    { 218, "NOISE WINDOW", g_ctls_218, (int)(sizeof(g_ctls_218)/sizeof(g_ctls_218[0])) },
};
extern const int g_dialogRegistryCount = (int)(sizeof(g_dialogRegistry)/sizeof(g_dialogRegistry[0]));
