#!/usr/bin/env python3
"""
Parses nodInc.h (XVT-Design-generated resource-ID header) to recover, for
every dialog/window resource ID, the list of its controls and each
control's widget type -- all encoded in the auto-generated constant names
themselves (e.g. WIN_116_CHECKBOX_68, GEOLOGY_OPTIONS_WINDOW_C13).

This does NOT recover pixel positions/sizes (that data lived in the
compiled .uid resource file, which isn't in this repo) but DOES recover
exact widget types for essentially every control in every one of this
app's ~150 dialogs, which is what matters for functional correctness.

Output: a C++ source file (qt_compat/dialog_registry.cpp) with a static
table consumed by qt_compat/xvt_compat.cpp.
"""
import re
import sys

TYPE_MAP = {
    'PUSHBUTTON': 'WC_PUSHBUTTON',
    'CHECKBOX': 'WC_CHECKBOX',
    'RADIOBUTTON': 'WC_RADIOBUTTON',
    'GROUPBOX': 'WC_GROUPBOX',
    'LISTEDIT': 'WC_LISTEDIT',
    'LISTBUTTON': 'WC_LISTBUTTON',
    'LBOX': 'WC_LBOX',
    'TREEVIEW': 'WC_TREEVIEW',
    'ICON': 'WC_ICON',
    'HSCROLL': 'WC_HSCROLL',
    'VSCROLL': 'WC_VSCROLL',
    'EDIT': 'WC_EDIT',
    'TEXT': 'WC_TEXT',
}
# Order matters: check longer/more-specific keywords before generic ones
TYPE_ORDER = ['PUSHBUTTON', 'RADIOBUTTON', 'CHECKBOX', 'GROUPBOX', 'LISTEDIT',
              'LISTBUTTON', 'LBOX', 'TREEVIEW', 'ICON', 'HSCROLL', 'VSCROLL',
              'EDIT', 'TEXT']

DEFINE_RE = re.compile(r'^#define\s+([A-Za-z_][A-Za-z0-9_]*)\s+(-?\d+)\s*$')
EH_RE = re.compile(r'^#define\s+(?:win|dlg)_\d+_eh\s+([A-Za-z_][A-Za-z0-9_]*)_eh\s*$')


def humanize(name):
    words = [w for w in name.split('_') if w]
    return ' '.join(words)


def classify_type(name):
    """Best-effort widget TYPE from the constant name; returns None (unknown/
    generic, resolved later at runtime) if no keyword matches."""
    tokens = name.split('_')
    for kw in TYPE_ORDER:
        if kw in tokens:
            return TYPE_MAP[kw]
    return None


def main():
    path = sys.argv[1] if len(sys.argv) > 1 else 'nodInc.h'
    out_path = sys.argv[2] if len(sys.argv) > 2 else 'dialog_registry.cpp'

    # Pass 1: collect the AUTHORITATIVE set of real window/dialog names from
    # the "#define win_NNN_eh SOMENAME_eh" / "#define dlg_NNN_eh SOMENAME_eh"
    # declarations at the top of nodInc.h. This is far more reliable than
    # guessing "window start" from absence of a control-type keyword (a
    # control whose name happens to use an unrecognized keyword, e.g.
    # PROFILE_WINDOW_CUSTOM_50, would otherwise be misdetected as a new
    # window and corrupt everything parsed after it).
    real_windows = set()
    with open(path, 'r', errors='replace') as f:
        for line in f:
            m = EH_RE.match(line.strip())
            if m:
                real_windows.add(m.group(1))
    print(f"Found {len(real_windows)} real window/dialog names via _eh declarations", file=sys.stderr)

    # Pass 2: walk all #define NAME VALUE lines; NAME in real_windows starts
    # a new window block, everything else until the next such NAME is one
    # of its controls (type guessed from the name, else unknown/generic).
    windows = {}
    order = []
    current = None

    with open(path, 'r', errors='replace') as f:
        for line in f:
            line = line.strip()
            m = DEFINE_RE.match(line)
            if not m:
                continue
            name, val = m.group(1), int(m.group(2))
            if name in real_windows:
                current = val
                if val not in windows:
                    windows[val] = {'name': name, 'controls': []}
                    order.append(val)
                continue
            if current is None:
                continue
            kind = classify_type(name)
            windows[current]['controls'].append((val, kind, name))

    total_ctls = sum(len(w['controls']) for w in windows.values())
    nonempty = [w for w in order if windows[w]['controls']]
    print(f"Parsed {len(order)} window/resource blocks, "
          f"{len(nonempty)} with >=1 control, {total_ctls} controls total",
          file=sys.stderr)

    with open(out_path, 'w') as out:
        out.write("""/* ============================================================================
 * XVT -> Qt COMPATIBILITY LAYER  (flagged file: see qt_compat/README.md)
 *
 * AUTO-GENERATED by scratchpad/gen_dialog_registry.py from nodInc.h -- DO
 * NOT HAND-EDIT. Regenerate by re-running that script against nodInc.h.
 *
 * nodInc.h's constant names were themselves auto-generated by XVT-Design
 * from the (missing, see qt_compat/README.md) compiled resource file, in
 * the form <WINDOW>_<WIDGETTYPE>_<seq>, e.g. WIN_116_CHECKBOX_68 or
 * GEOLOGY_OPTIONS_WINDOW_C13. That means the exact widget TYPE of nearly
 * every control in every one of this app's ~150 dialogs is recoverable
 * from the header alone, even though exact pixel positions/sizes are not
 * (those lived only in the missing resource file). This table is that
 * recovered type information, consumed by xvt_compat.cpp to build each
 * dialog's real controls (instead of an empty placeholder window) the
 * first time the app asks for it.
 * ============================================================================
 */
#include "xvt_types.h"

struct DialogCtlEntry { int ctlId; WIN_TYPE type; const char *label; };
struct DialogEntry { long resId; const char *title; const DialogCtlEntry *ctls; int numCtls; };

""")
        for resId in order:
            w = windows[resId]
            if not w['controls']:
                continue
            arr_name = f"g_ctls_{resId}"
            out.write(f"static const DialogCtlEntry {arr_name}[] = {{\n")
            for ctlId, kind, name in w['controls']:
                type_expr = kind if kind else 'W_NONE'
                label = humanize(name).replace('"', '\\"')
                out.write(f'    {{ {ctlId}, {type_expr}, "{label}" }},\n')
            out.write("};\n\n")

        out.write("const DialogEntry g_dialogRegistry[] = {\n")
        for resId in order:
            w = windows[resId]
            if not w['controls']:
                continue
            arr_name = f"g_ctls_{resId}"
            title = humanize(w['name']).replace('"', '\\"')
            out.write(f'    {{ {resId}, "{title}", {arr_name}, '
                      f'(int)(sizeof({arr_name})/sizeof({arr_name}[0])) }},\n')
        out.write("};\n")
        out.write("const int g_dialogRegistryCount = "
                   "(int)(sizeof(g_dialogRegistry)/sizeof(g_dialogRegistry[0]));\n")

    print(f"Wrote {out_path}", file=sys.stderr)


if __name__ == '__main__':
    main()
